/**
 * Aquaculture Domain Terminology
 *
 * 수산과학 연구 전문 용어 사전
 * - 양식, 수산 생물, 실험 설계에 특화된 용어
 */

import type { TerminologyDictionary } from '../terminology-types'
import type { GuidedQuestion, CategoryDefinition } from '@/types/smart-flow'

export const aquaculture: TerminologyDictionary = {
  domain: 'aquaculture',
  displayName: '수산과학',

  variables: {
    group: {
      title: '실험구 변수',
      description: '비교할 실험구를 정의하는 범주형 변수 (예: 양식장, 처리구, 사료 종류)',
      shortLabel: '실험구'
    },
    dependent: {
      title: '측정값 (Y)',
      description: '실험구 간 비교할 측정값 (예: 어체 중량, 성장률, 생존율)',
      shortLabel: '측정값'
    },
    independent: {
      title: '요인 변수 (X)',
      description: '예측 요인 변수 (예: 수온, 염분도, 용존산소)',
      shortLabel: '요인 변수'
    },
    factor: {
      title: '처리 조건',
      description: '실험 처리 조건 (예: 사료 종류, 수온 수준, 밀도)',
      shortLabel: '처리 조건'
    },
    covariate: {
      title: '공변량',
      description: '통제 변수 (예: 초기 체중, 초기 전장)',
      shortLabel: '공변량'
    },
    time: {
      title: '시간 변수',
      description: '시간 경과 변수 (예: 사육일수, 측정 주차)',
      shortLabel: '시간'
    },
    event: {
      title: '사건 변수',
      description: '발생 사건 (예: 폐사 여부, 성숙 도달)',
      shortLabel: '사건'
    },
    pairedFirst: {
      title: '처리 전 / 시점 1',
      description: '첫 번째 측정값 (예: 처리 전 체중)',
      shortLabel: '처리 전'
    },
    pairedSecond: {
      title: '처리 후 / 시점 2',
      description: '두 번째 측정값 (예: 처리 후 체중)',
      shortLabel: '처리 후'
    },
    correlation: {
      title: '연속형 변수',
      description: '상관분석할 연속형 변수 (예: 체중, 전장, 수온)',
      shortLabel: '변수'
    }
  },

  validation: {
    groupRequired: '실험구 변수를 선택해야 합니다',
    dependentRequired: '측정값을 선택해야 합니다',
    independentRequired: '요인 변수를 선택해야 합니다',
    factorRequired: '처리 조건을 선택해야 합니다',
    twoGroupsRequired: (current: number) =>
      `t-검정은 정확히 2개 그룹이 필요합니다 (현재 ${current}개)`,
    minVariablesRequired: (min: number) =>
      `최소 ${min}개의 변수가 필요합니다`,
    maxVariablesExceeded: (max: number) =>
      `최대 ${max}개까지만 선택할 수 있습니다`,
    differentVariablesRequired: '서로 다른 변수를 선택하세요',
    noNumericVariables: '연속형 변수가 없습니다',
    noCategoricalVariables: '범주형 변수가 없습니다'
  },

  success: {
    allVariablesSelected: '모든 변수가 선택되었습니다. 분석을 시작할 수 있습니다.',
    readyForAnalysis: '분석 준비 완료',
    variablesSelected: (count: number) =>
      `${count}개 변수 선택됨. 상관분석을 시작할 수 있습니다.`,
    correlationPairsCount: (count: number) =>
      `${count}개 상관계수 쌍이 계산됩니다`,
    modelReady: (type: 'simple' | 'multiple', predictors: number) =>
      `${type === 'simple' ? '단순' : '다중'}회귀 모델 준비 완료. ${predictors}개 예측변수 선택됨.`
  },

  selectorUI: {
    titles: {
      groupComparison: '실험구 비교 변수 선택',
      oneSample: '일표본 t-검정 변수 선택',
      paired: '대응 표본 변수 선택',
      correlation: '상관분석 변수 선택',
      multipleRegression: '다중회귀 변수 선택',
      twoWayAnova: '이원 ANOVA 변수 선택'
    },
    descriptions: {
      groupComparison: '실험구 변수와 측정값을 선택하세요 (예: 양식장별 어체 중량 비교)',
      oneSample: '검정할 측정값과 기준값을 입력하세요 (예: 평균 어체 중량 100g와 비교)',
      paired: '동일 개체의 두 측정값을 선택하세요 (예: 처리 전/후 어체 중량)',
      correlation: '상관관계를 분석할 2개 이상의 연속형 변수를 선택하세요 (예: 체중, 전장, 수온)',
      multipleRegression: '측정값(Y)과 요인 변수(X)를 선택하세요 (예: 성장률을 수온과 염분도로 예측)',
      twoWayAnova: '2개의 처리 조건과 1개의 측정값을 선택하세요'
    },
    buttons: {
      back: '이전',
      runAnalysis: '분석 시작',
      selectAll: '전체 선택',
      clear: '선택 해제',
      swap: '순서 바꾸기'
    },
    labels: {
      selected: '선택됨',
      compare: '비교:',
      across: '실험구별',
      model: '모델:',
      levels: '수준',
      groups: 'groups',
      numeric: 'numeric',
      range: 'Range',
      mean: 'Mean'
    }
  },

  smartFlow: {
    stepTitles: {
      dataUpload: '데이터 업로드',
      dataExploration: '데이터 탐색',
      purposeInput: '분석 방법 선택',
      variableSelection: '변수 선택',
      analysisExecution: '분석 실행',
      results: '결과 확인'
    },
    stepShortLabels: {
      exploration: '탐색',
      method: '방법',
      variable: '변수',
      analysis: '분석'
    },
    statusMessages: {
      analyzing: '데이터 분석 중...',
      analysisComplete: '분석이 완료되었습니다',
      uploadingData: '데이터 업로드 중...',
      validatingData: '데이터 검증 중...'
    },
    emptyStates: {
      dataRequired: '데이터가 필요합니다',
      dataRequiredDescription: '먼저 데이터를 업로드해주세요.',
    },
    aiVariables: {
      title: 'AI 추천 변수',
      roles: {
        dependent: '종속:',
        group: '집단:',
        factors: '요인:',
        independent: '독립:',
        covariate: '공변량:',
      },
    },
    floatingNav: {
      toMethod: '분석 방법 선택으로',
      toVariables: '변수 선택으로',
      toExecution: '분석 실행으로',
      runAnalysis: '분석 실행',
      defaultNext: '다음 단계로',
    },
    errors: {
      uploadFailed: (message: string) => `데이터 업로드 중 오류가 발생했습니다: ${message}`,
      retryLabel: '다시 시도하기',
    },
    modeBanners: {
      reanalysis: {
        description: '이전 설정으로 새 데이터를 분석합니다. 아래에서 데이터를 업로드하세요.',
      },
      quickAnalysis: {
        badge: '빠른 분석',
        description: '데이터를 업로드하면 바로 변수 선택으로 이동합니다.',
        normalMode: '일반 분석',
        changeMethod: '방법 변경',
      },
    },
    buttons: {
      runAnalysis: '분석 시작',
      reanalyze: '다른 데이터로 재분석',
      downloadResults: '결과 다운로드',
      backToHub: '처음으로'
    },
    resultSections: {
      effectSizeDetail: '효과크기 상세'
    },
    executionStages: {
      prepare: { label: '분석 환경 준비', message: '분석 환경 준비 중...' },
      preprocess: { label: '데이터 전처리', message: '데이터 전처리 중...' },
      assumptions: { label: '통계적 가정 검증', message: '통계적 가정 검증 중...' },
      analysis: { label: '통계 분석 실행', message: '통계 분석 실행 중...' },
      additional: { label: '추가 통계량 계산', message: '추가 통계량 계산 중...' },
      finalize: { label: '결과 정리', message: '결과 정리 중...' }
    },
    layout: {
      appTitle: 'NIFS 통계 분석',
      historyTitle: '분석 히스토리',
      historyClose: '히스토리 닫기',
      historyCount: (n: number) => `히스토리 (${n}개)`,
      aiChatbot: 'AI 챗봇',
      helpLabel: '도움말',
      settingsLabel: '설정',
      nextStep: '다음 단계로',
      analyzingDefault: '분석 중...',
      floatingNavDisabledHint: '데이터 파일을 업로드하면 활성화됩니다',
      dataSizeGuide: '데이터 크기 가이드',
      currentLimits: '현재 제한사항',
      memoryRecommendation: '메모리별 권장 크기',
      detectedMemory: (gb: number) => `→ 감지된 메모리: ${gb}GB`,
      limitFileSize: '최대 파일: 50MB',
      limitDataSize: '최대 데이터: 100,000행 × 1,000열',
      limitRecommended: '권장: 10,000행 이하',
      memoryTier4GB: '4GB RAM: ~10,000행',
      memoryTier8GB: '8GB RAM: ~30,000행',
      memoryTier16GB: '16GB RAM: ~60,000행',
      stepTooltip: (stepName: string) => `${stepName} 단계로 이동`,
    },
    execution: {
      runningTitle: '분석 수행 중',
      resumeButton: '계속',
      pauseButton: '일시정지',
      cancelButton: '취소',
      pauseDisabledTooltip: '75% 이후에는 일시정지할 수 없습니다',
      cancelConfirm: '정말 취소하시겠습니까?\n현재까지 계산된 결과는 저장되지 않습니다.',
      logSectionLabel: (n: number) => `상세 실행 로그 (${n}개)`,
      noLogs: '로그가 없습니다',
      dataRequired: '분석에 필요한 데이터나 방법이 선택되지 않았습니다.',
      unknownError: '알 수 없는 오류가 발생했습니다',
      estimatedTimeRemaining: (seconds: number) => `예상 남은 시간: ${seconds}초`,
    },
    executionLogs: {
      stageStart: (label: string) => `${label} 시작`,
      engineReadyCached: '통계 엔진 준비 완료 (캐시됨)',
      engineLoading: '통계 엔진을 불러오는 중... (3-5초 소요)',
      engineReady: '통계 엔진 준비 완료',
      dataLoaded: (n: number) => `데이터 로드 완료 (n=${n})`,
      missingHandled: (count: number) => `결측값 처리 완료 (제거: ${count}개)`,
      normalityTestStart: '정규성 검정 (Shapiro-Wilk) 시작...',
      normalityTestDone: (p: string) => `정규성 검정 완료 (p=${p})`,
      normalityTestFailed: '정규성 검정 실패 (데이터 부족 또는 오류)',
      homogeneityTestStart: '등분산성 검정 (Levene) 시작...',
      homogeneityTestDone: (p: string) => `등분산성 검정 완료 (p=${p})`,
      homogeneityTestFailed: '등분산성 검정 실패 (데이터 부족 또는 오류)',
      assumptionSkipped: '가정 검정 스킵 (조건 미충족)',
      methodExecuting: (name: string) => `${name} 실행`,
      aiSettingsApplied: (alpha: number) => `AI 추천 설정 적용: α=${alpha}`,
      aiPostHoc: (method: string) => `ℹ️ AI 추천 사후검정: ${method} (향후 지원 예정)`,
      aiAlternative: (direction: string) => `ℹ️ AI 추천 검정 방향: ${direction} (향후 지원 예정)`,
      effectSizeDone: '효과크기 계산 완료',
      confidenceIntervalDone: '신뢰구간 계산 완료',
      analysisDone: '분석 완료!',
      totalTime: (seconds: string) => `총 소요 시간: ${seconds}초`,
      errorPrefix: (message: string) => `❌ 오류: ${message}`,
      userCancelled: '사용자가 분석을 취소했습니다',
      locale: 'ko-KR',
    },
  },

  purposeInput: {
    purposes: {
      compare: {
        title: '그룹 간 차이 비교',
        description: '두 개 이상의 그룹을 비교하여 평균이나 비율의 차이를 검정합니다.',
        examples: '예: 양식장별 어류 성장률 비교, 사료 종류에 따른 체중 증가 비교, 해역별 수온 차이'
      },
      relationship: {
        title: '변수 간 관계 분석',
        description: '두 개 이상의 변수 사이의 상관관계나 연관성을 분석합니다.',
        examples: '예: 수온과 어류 성장률의 관계, 염분과 생존율의 관계, 체장과 체중의 관계'
      },
      distribution: {
        title: '분포와 빈도 분석',
        description: '데이터의 분포 형태를 파악하고 각 범주의 빈도를 분석합니다.',
        examples: '예: 어류 체장 분포, 어종별 어획량 비율, 해역별 플랑크톤 밀도 분포'
      },
      prediction: {
        title: '예측 모델링',
        description: '독립변수를 사용하여 종속변수를 예측하는 모델을 만듭니다.',
        examples: '예: 수온으로 어획량 예측, 사료량으로 성장률 예측, 환경요인으로 폐사율 예측'
      },
      timeseries: {
        title: '시계열 분석',
        description: '시간에 따른 데이터의 변화 패턴을 분석하고 미래를 예측합니다.',
        examples: '예: 월별 어획량 추이, 연도별 양식 생산량 변화, 계절별 수온 패턴'
      },
      survival: {
        title: '생존 분석',
        description: '시간에 따른 사건 발생까지의 기간을 분석하고 위험 요인을 파악합니다.',
        examples: '예: 치어 생존기간, 양식 시설 내구연수, 질병 발생 후 폐사까지 시간'
      },
      multivariate: {
        title: '다변량 분석',
        description: '여러 변수를 동시에 분석하여 차원 축소, 요인 추출, 군집화를 수행합니다.',
        examples: '예: 수질 지표 차원 축소(PCA), 양식장 유형화(군집), 어종 분류(판별분석)'
      },
      utility: {
        title: '연구 설계 도구',
        description: '표본 크기 계산, 검정력 분석, 측정 도구 신뢰도 평가를 수행합니다.',
        examples: '예: 실험 설계 시 필요 표본수, 설문지 신뢰도(Cronbach α), 검정력 계산'
      }
    },
    inputModes: {
      aiRecommend: 'AI가 추천',
      directSelect: '직접 선택',
      modeAriaLabel: '분석 방법 선택 모드'
    },
    buttons: {
      back: '뒤로',
      allMethods: '전체 분석 방법',
      useThisMethod: '이 방법으로 분석하기'
    },
    labels: {
      selectionPrefix: '선택:',
      directBadge: '직접 선택',
      purposeHeading: '어떤 분석을 하고 싶으신가요?'
    },
    messages: {
      purposeHelp: '8개 중 하나의 분석 목적을 선택하세요. 선택하면 단계별 질문을 통해 최적의 통계 방법을 추천합니다.',
      guidanceAlert: '위에서 분석 목적을 선택하면 단계별 질문을 통해 최적의 통계 방법을 추천합니다.',
      aiRecommendError: '추천 결과를 생성하지 못했습니다. 다시 시도해주세요.',
      genericError: '오류가 발생했습니다. 다시 시도해주세요.',
    },
    aiLabels: {
      recommendTitle: 'AI 추천 분석',
    },
  },

  fitScore: {
    levels: {
      excellent: { label: '매우 적합', shortLabel: '최적', description: '데이터에 매우 적합합니다' },
      good: { label: '적합', shortLabel: '적합', description: '데이터와 잘 맞습니다' },
      caution: { label: '주의 필요', shortLabel: '주의', description: '일부 조건이 충족되지 않습니다' },
      poor: { label: '부적합', shortLabel: '부적합', description: '다른 방법을 고려하세요' },
      unknown: { label: '평가 불가', shortLabel: '평가 불가', description: '데이터 정보가 부족합니다' },
    },
    confidenceLabel: '신뢰도',
  },

  analysisInfo: {
    cardTitle: '분석 정보',
    labels: {
      fileName: '파일명',
      dataSize: '데이터 크기',
      method: '분석 방법',
      analysisTime: '분석 시간',
      dataQuality: '데이터 품질',
      assumptions: '가정 검정',
      variables: '변수 구성',
    },
    variableRoles: {
      dependent: '종속변수',
      independent: '독립변수',
      group: '그룹변수',
      factor: 'Factor 변수',
      paired: 'Paired 변수',
    },
    dataQuality: {
      missingValues: (count: number, percent: string) => `결측값 ${count}개 (${percent}%)`,
      duplicateRows: (count: number) => `중복 행 ${count}개`,
      warnings: (count: number) => `${count}개 경고`,
    },
    assumptions: {
      normality: '정규성',
      homogeneity: '등분산성',
      independence: '독립성',
      met: '충족',
      partialViolation: '일부 위반',
      allGroupsNormal: '모든 그룹 정규',
      someGroupsNonNormal: '일부 그룹 비정규',
    },
    units: {
      rows: '행',
      nVariables: (count: number) => `${count}개 변수`,
    },
  },

  history: {
    empty: {
      title: '분석 히스토리가 없습니다',
      description: '완료된 분석이 자동으로 저장됩니다',
    },
    recordCount: (n: number) => `${n}개 기록`,
    buttons: {
      saveCurrent: '현재 분석 저장',
      clearAll: '전체 삭제',
      cancel: '취소',
      save: '저장',
      delete: '삭제',
    },
    labels: {
      filterByMethod: '분석 방법 필터',
      showAll: '전체 보기',
      searchPlaceholder: '히스토리 검색...',
      noMethod: '분석 방법 없음',
      noPurpose: '분석 목적 없음',
      current: '현재',
      rows: '행',
      pValue: 'p-value:',
      effectSize: '효과크기:',
    },
    tooltips: {
      viewResults: '저장된 결과 보기',
      reanalyze: '이 방법으로 새 데이터 분석',
      delete: '삭제',
      pin: '상단에 고정',
      unpin: '고정 해제',
      maxPinned: (max: number) => `최대 ${max}개까지 고정할 수 있습니다.`,
      exportReport: '보고서 내보내기',
    },
    dialogs: {
      deleteTitle: '분석 히스토리 삭제',
      deleteDescription: '이 분석 히스토리를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
      clearTitle: '전체 히스토리 삭제',
      clearDescription: (count: number) => `모든 분석 히스토리(${count}개)를 삭제하시겠습니까?\n이 작업은 되돌릴 수 없습니다.`,
      saveTitle: '현재 분석 저장',
      saveDescription: '현재 분석에 이름을 지정하여 저장합니다.',
      analysisName: '분석 이름',
      savePlaceholder: '예: 2024년 실험 데이터 t-검정',
    },
  },

  hub: {
    hero: {
      heading: '데이터에서 인사이트까지,',
      subheading: '과학적으로.',
      description: 'CSV, Excel 파일을 업로드하면 AI가 데이터 특성을 분석하고 최적의 통계 방법을 추천합니다. 전문가 수준의 분석을 몇 번의 클릭으로.',
      statMethods: (count: number) => `${count}개 분석 도구`,
      statCategories: (count: number) => `${count}개 카테고리`,
      statAi: 'AI 추천',
      uploadButton: '데이터 업로드',
      browseButton: '분석 방법',
    },
    chatInput: {
      heading: '무엇을 분석하고 싶으신가요?',
      placeholder: '분석하고 싶은 내용을 입력하세요...',
      sendAriaLabel: '보내기',
      processingMessage: '최적 분석 방향을 파악하고 있습니다...',
      uploadAriaLabel: '데이터 파일 업로드',
      uploadTitle: 'CSV / Excel 파일 업로드',
    },
    tracks: {
      directAnalysis: {
        title: '직접 분석',
        description: '분석 방법을 알고 있다면 바로 시작하세요',
        example: 't-test 하고 싶어',
      },
      dataConsultation: {
        title: '데이터 상담',
        description: '데이터를 넣고 AI와 상담하며 분석하세요',
        example: '데이터를 넣고 어떤 분석이 좋을지 알려줘',
      },
      experimentDesign: {
        title: '실험 설계',
        description: '실험 계획, 표본 크기, 검정력을 분석하세요',
        example: '적절한 표본 크기는?',
      },
    },
    experimentNotReady: '실험 설계 기능은 준비 중입니다. 데이터 상담으로 안내해 드릴게요.',
    cards: {
      methodsTitle: '분석 도구',
      methodsDescription: (categories: number) => `T-검정, ANOVA, 회귀분석 등 ${categories}개 카테고리의 전체 목록을 탐색합니다`,
      methodsLink: '탐색하기',
      aiTitle: 'AI 추천',
      aiDescription: '분석 목적을 자연어로 설명하면 데이터에 맞는 최적의 방법을 추천합니다',
      aiLink: '시작하기',
      recentTitle: '최근 분석',
      viewAll: '전체 보기',
      historyLabel: '히스토리',
      unknownMethod: '알 수 없음',
      emptyTitle: '아직 분석 기록이 없습니다',
      emptyDescription: '첫 분석을 시작해보세요',
    },
    quickAnalysis: {
      title: '빠른 분석',
      emptyPlaceholder: '편집으로 추가',
      editTooltip: '빠른 분석 편집',
      editButton: '편집',
      frequentlyUsed: '자주 사용:',
    },
    aiSearch: {
      title: 'AI 분석 가이드',
      description: '실험 설계나 데이터를 설명해주시면 양식 연구에 맞는 통계법을 추천합니다.',
      placeholder: '예: "사료 A, B에 따른 넙치 성장률 비교" 또는 "수온과 용존산소량의 관계"',
      sendButton: '',
      startButton: '가이드 시작',
      alternatives: (count: number) => `외 ${count}개 대안`,
      detailedLink: '상세 가이드',
      recommendationBadge: '추천 방법',
      selectButton: '선택하기'
    },
    editDialog: {
      title: '빠른 분석 편집',
      selectedCount: (count: number) => `${count}개 선택됨`,
      cancel: '취소',
      save: '저장',
    },
    timeAgo: {
      justNow: '방금 전',
      minutesAgo: (n: number) => `${n}분 전`,
      hoursAgo: (n: number) => `${n}시간 전`,
      daysAgo: (n: number) => `${n}일 전`,
    },
    categoryLabels: {
      't-test': 'T-검정',
      'anova': '분산분석 (ANOVA)',
      'nonparametric': '비모수 검정',
      'correlation': '상관분석',
      'regression': '회귀분석',
      'chi-square': '범주형 분석',
      'descriptive': '기술통계',
      'timeseries': '시계열분석',
      'survival': '생존분석',
      'pca': '차원축소',
      'clustering': '군집분석',
      'advanced': '고급 분석',
      'design': '실험설계',
      'psychometrics': '심리측정',
    },
    entryPoints: {
      dataUpload: '데이터 업로드',
      aiRecommend: 'AI 추천',
      methodSelect: '방법 선택',
      history: '히스토리',
    },
    quickMethodNames: {
      't-test': 't-검정',
      'anova': 'ANOVA',
      'correlation': '상관분석',
      'regression': '회귀분석',
      'chi-square': '카이제곱',
      'paired-t-test': '대응표본 t-검정',
      'mann-whitney': 'Mann-Whitney U',
      'wilcoxon': 'Wilcoxon',
      'kruskal-wallis': 'Kruskal-Wallis',
      'fisher-exact': 'Fisher 정확 검정',
    },
  },

  guidedQuestions: {
    assumptionLabels: {
      normality: '정규성',
      homogeneity: '등분산성',
    },
    assumptionStatus: {
      met: '충족',
      violated: '위반',
      needsCheck: '확인 필요',
    },
    badges: {
      manualOverride: '수동 설정',
    },
    buttons: {
      modify: '수정하기',
      autoApply: '자동 적용',
      browseAll: '전체 방법에서 직접 선택',
      directSelect: '직접 선택',
      back: '뒤로',
      next: '다음',
      close: '닫기',
      collapse: '숨기기',
      expand: '펴기',
    },
    tooltips: {
      switchToClassic: '클래식 모드로 전환',
      switchToConversational: '대화형 모드로 전환',
    },
    sections: {
      assumptionResults: '가정 검정 결과',
      advancedOptions: '고급 옵션',
    },
    card: {
      title: '데이터 조건을 알려주세요',
      description: '정확한 분석 방법 추천을 위해 몇 가지 질문에 답해주세요',
    },
  },

  dataExploration: {
    empty: {
      title: '데이터를 업로드하여 시작하세요',
      description: 'CSV 또는 Excel 파일을 업로드하면 데이터 요약, 분포 시각화, 상관관계 분석을 자동으로 수행합니다.',
    },
    features: {
      descriptiveTitle: '기초 통계량',
      descriptiveDesc: '평균, 표준편차, 사분위수, 왜도/첨도 등',
      distributionTitle: '분포 시각화',
      distributionDesc: '히스토그램, 박스플롯, 이상치 탐지',
      correlationTitle: '상관관계 분석',
      correlationDesc: '산점도, 상관 히트맵, 추세선',
    },
    tabs: {
      dataSummary: '데이터 요약',
      fullDataView: (n: number) => `전체 데이터 보기 (${n}행)`,
      statistics: '기초 통계량',
      preview: '데이터 미리보기',
    },
    headers: {
      variableName: '변수명',
      count: 'N',
      mean: '평균',
      stdDev: '표준편차',
      median: '중앙값',
      min: '최소',
      max: '최대',
      skewness: '왜도',
      kurtosis: '첨도',
      outliers: '이상치',
    },
    interpretGuide: {
      title: '해석 기준:',
      skewness: '왜도: |값| > 2 → 심한 비대칭 (⚠ 표시)',
      kurtosis: '첨도: |값| > 7 → 극단값 많음 (⚠ 표시)',
      outlierDef: '이상치: IQR × 1.5 범위 벗어난 값',
      nDef: 'N: 유효한 값의 개수 (결측 제외)',
    },
    outlier: {
      detected: (varCount: number, totalCount: number) => `이상치 감지: ${varCount}개 변수에서 총 ${totalCount}개`,
      variableDetail: (name: string, count: number) => `${name}(${count}개)`,
      moreVars: (count: number) => `외 ${count}개 변수`,
      count: (n: number) => `${n}개`,
      info: (count: number, lower: string, upper: string) => `이상치: ${count}개 발견 (범위: <${lower} 또는 >${upper})`,
    },
    chartTypes: {
      histogram: '히스토그램',
      boxplot: '박스플롯',
      ariaLabel: '차트 타입 선택',
    },
    distribution: {
      title: '데이터 분포 시각화',
      description: '수치형 변수들의 분포를 히스토그램 또는 박스플롯으로 확인합니다',
    },
    histogram: {
      title: (varName: string) => `${varName} 분포`,
      yAxisLabel: '빈도',
    },
    boxplot: {
      selectInstruction: '변수를 클릭하여 비교할 변수를 선택하세요 (최대 8개)',
      singleTitle: (varName: string) => `${varName} 박스플롯`,
      multipleTitle: (count: number) => `변수 분포 비교 (${count}개)`,
    },
    scatterTabs: {
      scatter: '산점도',
      heatmap: '상관 히트맵',
    },
    scatter: {
      variableRelation: '변수 관계 분석',
      xAxis: 'X축 (독립변수)',
      yAxis: 'Y축 (종속변수)',
    },
    correlation: {
      coefficient: '상관계수',
      determination: '결정계수',
      strong: '강한 상관',
      medium: '중간 상관',
      weak: '약한 상관',
    },
    heatmap: {
      title: '상관계수 히트맵',
      description: '모든 수치형 변수 쌍의 상관관계를 시각화합니다',
      calculating: '상관계수 계산 중...',
      variableCount: (n: number) => `${n}개 변수 분석`,
    },
    heatmapGuide: {
      title: '상관계수 해석:',
      strongPositive: 'r = +1: 강한 양의 상관',
      strongNegative: 'r = -1: 강한 음의 상관',
      noCorrelation: 'r = 0: 상관 없음',
      veryStrong: '|r| >= 0.7: 매우 강한 상관',
    },
    strongCorrelations: {
      title: '주요 상관관계 (|r| >= 0.5)',
    },
    strength: {
      weak: '약한',
      medium: '중간',
      strong: '강한',
      veryStrong: '매우 강한',
    },
    assumptions: {
      loading: '통계적 가정 검증 중...',
      loadingDescription: '정규성, 등분산성 검정을 수행하고 있습니다. 잠시만 기다려주세요.',
      badge: '참고',
      title: '통계적 가정 검증',
      description: '이 결과를 바탕으로 적절한 통계 검정 방법을 선택하세요.',
      passed: '통과',
      failed: '불충족',
    },
    normality: {
      title: '정규성 검정 (Shapiro-Wilk)',
      normal: '정규분포',
      nonNormal: '비정규분포',
      statLabel: '통계량: ',
      normalInterpretation: '✓ 정규분포 가정을 만족합니다 (p ≥ 0.05). 모수 검정 사용 가능합니다.',
      nonNormalInterpretation: '⚠ 정규분포 가정을 만족하지 않습니다 (p < 0.05). 비모수 검정 고려가 필요합니다.',
    },
    homogeneity: {
      title: '등분산성 검정 (Levene)',
      equal: '등분산',
      unequal: '이분산',
      statLabel: '통계량: ',
      equalInterpretation: '✓ 등분산 가정을 만족합니다 (p ≥ 0.05).',
      unequalInterpretation: '⚠ 등분산 가정을 만족하지 않습니다 (p < 0.05). Welch 검정 고려가 필요합니다.',
    },
    highlight: {
      description: (column: string, count: number) => `${column} 변수의 이상치 ${count}개가 강조 표시되었습니다`,
      clearButton: '하이라이트 해제',
      notFound: '선택한 행을 찾을 수 없습니다. 데이터가 변경되었는지 확인해주세요.',
    },
    preview: {
      title: '데이터 미리보기',
      topN: (n: number) => `상위 ${n}행`,
      viewAll: (n: number) => `전체 보기 (${n}행)`,
      fullDataInstruction: (n: number) => `전체 데이터(${n}행)를 보려면 상단의 "전체 데이터 보기" 버튼을 클릭하세요.`,
    },
    warnings: {
      fewNumericVars: '수치형 변수가 2개 미만입니다. 상관분석이 제한됩니다.',
      correlationRequires: '상관분석에는 수치형 변수가 2개 이상 필요합니다.',
      currentStatus: (numeric: number, categorical: number) => `현재: 수치형 ${numeric}개, 범주형 ${categorical}개`,
      nextStepHint: '다음 단계에서 적합한 분석 방법을 선택할 수 있습니다.',
    },
    replaceMode: {
      title: '다른 데이터 파일을 업로드하세요',
      cancel: '취소',
      button: '데이터 교체',
    },
    fallbackFileName: '업로드된 데이터',
  },

  results: {
    effectSizeLabels: {
      small: '작음',
      medium: '중간',
      large: '큼',
      veryLarge: '매우 큼',
    },
    noResults: '분석을 먼저 실행해주세요.',
    noResultsDescription: '통계 분석을 먼저 실행해 주세요.',
    conclusion: {
      assumptionWarning: '⚠️ 일부 가정 미충족 - 결과 해석에 주의 필요',
      significant: '✓ 통계적으로 유의한 차이가 있습니다',
      notSignificant: '통계적으로 유의한 차이가 없습니다',
    },
    statistics: {
      statistic: '통계량',
      statisticTooltip: '검정통계량: 귀무가설 하에서 표본 데이터가 얼마나 극단적인지 나타냅니다.',
      pValue: '유의확률',
      pValueTooltip: 'p < 0.05이면 통계적으로 유의합니다.',
      effectSize: '효과크기',
      effectSizeTooltip: '효과크기: 실질적인 효과의 크기를 나타냅니다. 작음(<0.2), 중간(0.2-0.5), 큼(>0.5)',
      significant: '유의함',
      notSignificant: '유의하지 않음',
    },
    ai: {
      label: 'AI 해석',
      loading: 'AI가 결과를 해석하고 있어요...',
      detailedLabel: '상세 해석',
      reinterpret: '다시 해석',
      retry: '다시 시도',
      defaultError: 'AI 해석 중 오류가 발생했습니다.',
    },
    sections: {
      detailedResults: '상세 결과',
      confidenceInterval: '신뢰구간',
      apaFormat: 'APA 형식',
      diagnostics: '진단 & 권장',
      caution: '주의',
      recommendations: '권장사항',
      warnings: '주의사항',
      alternatives: '대안 분석 방법',
    },
    metadata: {
      file: '파일: ',
      data: '데이터: ',
      variables: '변수: ',
      rowsCols: (rows: number, cols: number) => `${rows}행 × ${cols}열`,
      analysisTime: '분석 실행 시각',
    },
    buttons: {
      saved: '저장됨',
      save: '저장',
      generating: '생성중...',
      pdf: 'PDF',
      copied: '복사됨',
      copy: '복사',
      saveTemplate: '템플릿으로 저장',
      reanalyze: '다른 데이터로 재분석',
      newAnalysis: '새 분석 시작',
      export: '내보내기',
      exporting: '내보내는 중...',
      exportDocx: 'Word 문서 (DOCX)',
      exportExcel: 'Excel 스프레드시트',
      exportHtml: 'HTML (.html)',
      exportWithOptions: '세부 옵션으로 내보내기',
      backToVariables: '변수 선택으로',
    },
    save: {
      defaultName: (date: string) => `분석 ${date}`,
      promptMessage: '분석 이름을 입력하세요:',
      success: '저장되었습니다',
      errorTitle: '저장 실패',
      unknownError: '알 수 없는 오류',
    },
    toast: {
      reanalyzeReady: '새 데이터를 업로드하세요',
      reanalyzeMethod: (name: string) => `${name} 분석이 준비되어 있습니다`,
      newAnalysis: '새 분석을 시작합니다',
      pdfSuccess: 'PDF 보고서가 생성되었습니다',
      pdfError: 'PDF 생성에 실패했습니다',
      exportSuccess: '내보내기가 완료되었습니다',
      exportError: '내보내기에 실패했습니다',
      copyWithAi: '결과 + AI 해석이 복사되었습니다',
      copySuccess: '결과가 복사되었습니다',
      copyError: '복사 실패',
      templateSaved: '템플릿이 저장되었습니다',
    },
    exportDialog: {
      title: '내보내기 옵션',
      description: '포함할 내용을 선택해 파일을 생성합니다.',
      formatLabel: '파일 형식',
      contentLabel: '포함 내용',
      includeInterpretation: '결과 해석',
      includeRawData: '원본 데이터 미리보기 (최대 200행)',
      includeMethodology: '분석 방법론',
      includeReferences: '참고문헌',
      cancel: '취소',
      confirm: '내보내기',
    },
    clipboard: {
      itemHeader: '항목',
      valueHeader: '값',
      statistic: (name: string) => `통계량 (${name})`,
      df: '자유도 (df)',
      effectSize: '효과크기',
      confidenceInterval: '95% 신뢰구간',
      interpretation: '해석:',
      aiInterpretation: 'AI 해석',
      aiSeparator: '--- AI 해석 ---',
    },
    followUp: {
      title: '추가 질문',
      userLabel: '질문',
      aiLabel: 'AI',
      placeholder: '궁금한 점을 질문하세요...',
      errorMessage: '후속 질문 처리 중 오류가 발생했습니다.',
      changeMethod: '다른 방법으로 분석하기',
      chips: [
        { label: '논문에 어떻게 쓰나요?', prompt: '이 결과를 APA 형식으로 논문에 어떻게 작성하면 되나요?' },
        { label: '효과크기 해석', prompt: '효과크기를 비전문가도 이해할 수 있게 쉽게 설명해주세요.' },
        { label: '가정 위반 대안', prompt: '가정 검정이 충족되지 않았을 때 어떤 대안적 분석 방법이 있나요?' },
        { label: '연구 한계점', prompt: '이 분석 결과의 한계점과 주의사항은 무엇인가요?' },
        { label: '다음 분석은?', prompt: '이 결과를 바탕으로 다음에 어떤 분석이나 조치를 하면 좋을까요?' },
      ],
    },
    confirm: {
      newAnalysis: {
        title: '새 분석을 시작할까요?',
        description: '현재 데이터와 결과가 모두 초기화됩니다. 이 작업은 되돌릴 수 없습니다.',
        confirm: '새 분석 시작',
        cancel: '취소',
      },
    },
  },

  dataUpload: {
    errors: {
      fileTooLarge: (maxMB: number) => `파일이 너무 큽니다. 최대 ${maxMB}MB까지 가능합니다.`,
      fileSizeExceeded: '파일 크기 초과',
      currentFileSize: (sizeMB: string) => `현재: ${sizeMB}MB`,
      validationFailed: '파일 검증 실패',
      noDataInFile: '파일에 데이터가 없습니다.',
      noDataTitle: '데이터 없음',
      noValidData: '파일에 처리 가능한 데이터가 없습니다',
      tooManyRows: (maxRows: string) => `데이터가 너무 많습니다. 최대 ${maxRows}행까지 가능합니다.`,
      dataSizeExceeded: '데이터 크기 초과',
      currentRowCount: (rows: string) => `현재: ${rows}행`,
      processingError: '파일 처리 중 오류가 발생했습니다.',
      excelValidationFailed: 'Excel 파일 검증 실패',
      excelFileError: 'Excel 파일 오류',
      excelProcessingError: 'Excel 파일 처리 중 오류가 발생했습니다.',
      unsupportedFormat: '지원하지 않는 파일 형식입니다.',
      unsupportedFormatTitle: '지원하지 않는 파일 형식',
      csvRequired: 'CSV 파일을 업로드해주세요',
      sheetProcessingError: 'Excel 시트 처리 중 오류가 발생했습니다.',
    },
    success: {
      fileUploaded: '파일 업로드 성공',
      excelFileUploaded: 'Excel 파일 업로드 성공',
      sheetLoaded: 'Excel 시트 로드 성공',
      dataLoaded: (rows: string) => `${rows}행의 데이터를 불러왔습니다`,
    },
    buttons: {
      selectFile: '파일 선택',
      changeFile: '파일 변경',
      uploading: '업로드 중...',
      loading: '불러오는 중...',
      cancel: '취소',
      loadSelectedSheet: '선택한 시트 불러오기',
      deleteRecentFile: '최근 파일 삭제',
    },
    labels: {
      dragOrClick: '파일을 드래그하거나 클릭하여 업로드',
      dropHere: '파일을 놓으세요',
      fileSpecifications: '최대 100,000행 | 지원 형식: CSV, Excel',
      recentFiles: '최근 업로드한 파일',
      recentFilesNote: '* 최근 파일을 클릭하면 파일 선택기가 열립니다.',
      recentFilesClickHint: '클릭 시 파일 선택창 열림',
      recentFileClickTitle: '브라우저 보안상 자동 로드 불가 — 클릭하면 파일 선택창이 열립니다',
      selectSheet: 'Excel 시트 선택',
      sheetsFound: (count: number) => `${count}개의 시트가 발견되었습니다. 분석할 시트를 선택하세요.`,
      selectSheetPlaceholder: '시트를 선택하세요',
      sheetInfo: (name: string, rows: string, cols: number) => `${name} (${rows}행 × ${cols}열)`,
      processing: (current: string, total: string) => `처리 중... ${current} / ${total}행`,
      estimatedTime: (seconds: number) => `예상 남은 시간: ${seconds}초`,
      analyzing: '파일을 분석하고 있습니다...',
      helpText: '첫 번째 행은 변수명(헤더)이어야 합니다. Excel 파일의 경우 여러 시트가 있으면 선택할 수 있습니다.',
      fileMetadata: (rows: string, size: string, time: string) => `${rows}행 · ${size} · ${time}`,
    },
    warnings: {
      highMemoryTitle: '메모리 사용량 높음',
      highMemoryDescription: '브라우저 메모리 사용량이 높습니다. 다른 탭을 닫거나 더 작은 데이터셋을 사용해주세요.',
    },
    toast: {
      selectSheet: '시트 선택',
      sheetsFoundDescription: (count: number) => `${count}개의 시트가 발견되었습니다. 분석할 시트를 선택하세요.`,
    },
  },

  dataValidation: {
    status: {
      dataRequired: '데이터를 먼저 업로드해주세요.',
      failed: '데이터 검증 실패',
      warningComplete: '데이터 검증 완료 (경고 있음)',
      readyComplete: '데이터 준비 완료',
    },
    labels: {
      sampleSize: '표본 크기',
      analyzableVariables: '분석 가능 변수',
      numeric: '수치형',
      categorical: '범주형',
      dataQuality: '데이터 품질',
      uploadedFile: '업로드 파일',
      missing: '결측',
      columnsCount: (count: number) => `${count}개 컬럼`,
      otherVariables: (count: number) => `외 ${count}개 변수...`,
    },
    badges: {
      largeSample: '대표본',
      smallSample: '소표본',
      numeric: '수치형',
      categorical: '범주형',
      idSequential: 'ID/일련번호',
    },
    quality: {
      perfect: '완벽',
      good: '양호',
      caution: '주의',
    },
    units: {
      count: '개',
    },
    sections: {
      needsAttention: '확인 필요 사항',
      variableSummary: '📋 변수 요약',
    },
    table: {
      variableName: '변수명',
      type: '유형',
      uniqueValues: '고유값',
      missing: '결측',
      excluded: '분석 제외',
    },
    idDetection: {
      label: '🔑 ID 제외:',
      heading: '🔑 ID/일련번호 감지:',
      explanation: '표시된 변수는 자동 생성된 식별자로 보입니다. 통계 분석에서 자동으로 제외됩니다.',
    },
    recommendations: {
      title: '💡 이 데이터로 할 수 있는 분석',
      hint: '💡 다음 단계에서 분석 목적을 선택하면 AI가 최적의 방법을 추천합니다.',
      twoGroupComparison: '2집단 비교 (t-검정, Mann-Whitney)',
      multiGroupComparison: '다집단 비교 (ANOVA, Kruskal-Wallis)',
      correlation: '상관분석 (Pearson, Spearman)',
      regression: '회귀분석 (예측 모델)',
      chiSquare: '카이제곱 검정 (범주형 연관성)',
    },
    warnings: {
      canContinue: '⚠ 경고 사항이 있지만 분석을 계속할 수 있습니다',
    },
    fallback: {
      noFileName: '파일명 없음',
    },
  },

  naturalLanguageInput: {
    description: '분석하고 싶은 내용을 자연스럽게 입력하세요. AI가 적합한 통계 방법을 추천해드립니다.',
    dataSummary: {
      dimension: (rows: number, cols: number) => `${rows}행 x ${cols}열`,
      numeric: (count: number) => `수치형 ${count}개`,
      categorical: (count: number) => `범주형 ${count}개`,
      privacyNotice: '원시 데이터는 전송되지 않으며, 요약 통계만 AI에 전달됩니다.',
    },
    input: {
      placeholder: '예: "두 그룹의 평균이 다른지 비교하고 싶어요"',
      sendHint: '전송',
      newlineHint: '줄바꿈',
    },
    examplesLabel: '예시:',
    examples: [
      '두 그룹의 평균 차이를 비교하고 싶어요',
      '변수 간의 상관관계를 알고 싶어요',
      '시간에 따른 추세를 분석하고 싶어요',
      '여러 그룹의 평균을 동시에 비교하고 싶어요',
    ],
    loadingMessages: [
      '데이터를 분석하고 있습니다...',
      '통계 방법을 비교하고 있습니다...',
      '최적의 분석 방법을 찾고 있습니다...',
    ],
    error: {
      title: '오류 발생',
    },
    aiAnalysis: {
      label: 'AI 분석',
    },
    recommendation: {
      badgeLabel: 'AI 추천',
      confidenceUnit: '% 확신',
      reasoningTitle: '추천 근거',
      variableAssignmentTitle: '변수 할당',
      preprocessingTitle: (count: number) => `전처리 제안 (${count}개)`,
      alternativesTitle: (count: number) => `다른 선택지 (${count}개)`,
      variableRoles: {
        dependent: '종속',
        independent: '독립',
        factor: '요인',
        covariate: '공변량',
        within: '피험자내',
        between: '피험자간',
      },
      assumptions: {
        normalityMet: '정규성 충족',
        normalityNotMet: '정규성 미충족',
        homogeneityMet: '등분산 충족',
        homogeneityNotMet: '등분산 미충족',
      },
    },
    buttons: {
      getRecommendation: '추천받기',
      analyzing: '분석 중...',
      goToGuided: '단계별 가이드로 이동',
      selectMethod: '이 방법으로 분석하기',
      retry: '다시 질문',
      select: '선택',
      guidedQuestions: '단계별 가이드',
      browseAll: '전체 목록 보기',
    },
    providers: {
      keyword: '키워드',
    },
  },

  methodSelector: {
    searchPlaceholder: '통계 방법 검색... (↑↓ 이동, Enter 선택)',
    methodCount: (count: number) => `${count}개 방법`,
    searchPrefix: '검색: ',
    selected: '선택됨: ',
    recommendedBadge: '추천',
    requirementNotMet: '요구사항 미충족',
    showBrief: '간략히 보기',
    showDetails: '자세히 보기',
    noDataProfile: '데이터 프로파일 정보가 없습니다',
    fitScoreDetails: '적합도 상세',
    sampleSizeRequirement: (rows: number, min: number) => `샘플 크기: ${rows}개 (최소 ${min}개 필요)`,
    numericVarsCount: (count: number) => `수치형 변수: ${count}개`,
    categoricalVarsCount: (count: number) => `범주형 변수: ${count}개`,
    assumptions: {
      normality: '정규성',
      homogeneity: '등분산성',
      needsTest: '검정 필요',
      met: '충족',
      notMet: '불충족',
    },
    aiRecommended: (count: number) => `AI 추천 (${count})`,
    otherMethods: (count: number) => `기타 방법 (${count})`,
    noSearchResults: (query: string) => `"${query}"에 해당하는 방법이 없습니다`,
    clearSearch: '검색 초기화',
  },

  methodBrowser: {
    compatibilityStatus: {
      warning: '주의',
      incompatible: '불가',
    },
    tooltips: {
      warning: '주의 필요',
      incompatible: '사용 불가',
    },
    aiRecommendation: {
      label: 'AI 추천',
      badge: '최적 매칭',
    },
    searchPlaceholder: '통계 방법 검색...',
    selectedLabel: '선택됨',
    selectedPrefix: '선택됨: ',
    methodsLabel: '개 방법',
    requirementsNotMet: '요구사항 미충족',
    useThisButton: '이 방법 사용',
    noResultsMessage: (query: string) => `"${query}"에 해당하는 방법이 없습니다`,
    clearSearchButton: '검색 초기화',
  },

  template: {
    saveTitle: '템플릿으로 저장',
    saveDescription: '현재 분석 설정을 템플릿으로 저장하면 나중에 새 데이터로 빠르게 동일 분석을 수행할 수 있습니다.',
    manageTitle: '템플릿 관리',
    manageDescription: '저장된 분석 템플릿을 관리하고 선택합니다',
    editTitle: '템플릿 수정',
    editDescription: '템플릿 이름과 설명을 수정합니다',
    savedTemplates: '저장된 템플릿',
    loading: '불러오는 중...',
    templateCount: (count: number) => `${count}개`,
    usageCount: (count: number) => `${count}회 사용`,
    usageCountShort: (count: number) => `${count}회`,
    methodCategories: {
      'descriptive': '기술통계',
      't-test': 't-검정',
      'anova': '분산분석',
      'regression': '회귀분석',
      'correlation': '상관분석',
      'chi-square': '카이제곱',
      'nonparametric': '비모수',
      'advanced': '고급분석',
      'timeseries': '시계열',
      'pca': 'PCA',
      'clustering': '군집분석',
      'psychometrics': '심리측정',
      'design': '실험설계',
      'survival': '생존분석',
    },
    variableLabels: {
      dependent: '종속변수',
      independent: '독립변수',
      group: '그룹변수',
      factor: '요인',
    },
    labels: {
      nameRequired: '템플릿 이름 *',
      descriptionOptional: '설명 (선택)',
      name: '이름',
      description: '설명',
    },
    placeholders: {
      name: '예: 실험 데이터 t-test',
      description: '나중에 참고할 메모를 입력하세요',
      search: '템플릿 검색...',
    },
    buttons: {
      cancel: '취소',
      save: '저장',
      saving: '저장 중...',
      edit: '수정',
      delete: '삭제',
      deleteAll: '모든 템플릿 삭제',
      deleteAllConfirm: '모두 삭제',
      viewAll: '전체보기',
    },
    errors: {
      nameRequired: '템플릿 이름을 입력해주세요.',
      settingsIncomplete: '분석 설정이 완료되지 않았습니다.',
      saveFailed: '저장 중 오류가 발생했습니다.',
    },
    sortOptions: {
      'recent': '최근 사용',
      'usage': '사용 빈도',
      'name': '이름',
      'created': '생성일',
    },
    timeAgo: {
      justNow: '방금 전',
      minutesAgo: (n: number) => `${n}분 전`,
      hoursAgo: (n: number) => `${n}시간 전`,
      daysAgo: (n: number) => `${n}일 전`,
    },
    empty: {
      title: '저장된 템플릿이 없습니다',
      description: '분석 완료 후 "템플릿으로 저장"을 클릭하세요',
    },
    dialogs: {
      deleteTitle: '템플릿 삭제',
      deleteConfirm: (name: string) => `"${name}" 템플릿을 삭제하시겠습니까?`,
      clearTitle: '모든 템플릿 삭제',
      clearConfirm: (count: number) => `저장된 모든 템플릿(${count}개)을 삭제하시겠습니까?`,
      irreversible: '이 작업은 되돌릴 수 없습니다.',
    },
  },

  validationDetails: {
    numericStats: {
      title: '수치형 변수 상세 통계',
      headers: {
        variableName: '변수명',
        mean: '평균',
        median: '중앙값',
        stdDev: '표준편차',
        cv: 'CV(%)',
        skewness: '왜도',
        kurtosis: '첨도',
        min: '최소값',
        max: '최대값',
        outliers: '이상치',
      },
      explanation: {
        cvLabel: 'CV (변동계수)',
        cvDescription: '표준편차를 평균으로 나눈 값의 백분율. 15% 이하면 안정적',
        skewnessLabel: '왜도',
        skewnessNormal: '|값| < 0.5 정규분포',
        skewnessModerate: '|값| < 1 약간 치우침',
        skewnessSevere: '|값| ≥ 1 심하게 치우침',
        kurtosisLabel: '첨도',
        kurtosisNormal: '|값| < 1 정규분포',
        kurtosisModerate: '|값| < 3 약간 뾰족/평평',
        kurtosisSevere: '|값| ≥ 3 매우 뾰족/평평',
      },
      problemGuide: {
        title: '데이터 문제 해결 가이드',
        skewnessTitle: '왜도 문제 (|왜도| ≥ 1) 해결 방법:',
        skewnessPositive: '양의 왜도 (오른쪽 꼬리): 로그 변환(log), 제곱근 변환(sqrt), Box-Cox 변환 적용',
        skewnessNegative: '음의 왜도 (왼쪽 꼬리): 제곱 변환, 지수 변환, 역수 변환 적용',
        skewnessAlternative: '대안: 비모수 검정 사용 (Mann-Whitney U, Kruskal-Wallis)',
        kurtosisTitle: '첨도 문제 (|첨도| ≥ 3) 해결 방법:',
        kurtosisHigh: '높은 첨도 (뾰족한 분포): 이상치 제거, Winsorization, Trimming 적용',
        kurtosisLow: '낮은 첨도 (평평한 분포): 데이터 범위 확인, 다봉분포 가능성 검토',
        kurtosisAlternative: '대안: 로버스트 통계 방법 사용, 부트스트랩 적용',
        outlierTitle: '이상치 문제 (10% 초과) 해결 방법:',
        outlierIdentify: '원인 파악: 입력 오류, 측정 오류, 실제 극단값 구분',
        outlierTreatment: '처리 방법: 제거, Winsorization (극단값을 경계값으로 대체), 변환',
        outlierAlternative: '대안: 로버스트 회귀, 중앙값 기반 분석, M-추정량 사용',
        generalTitle: '일반 권장사항:',
        generalCompare: '변환 전후 결과를 비교하여 최적 방법 선택',
        generalNonParametric: '여러 문제가 동시에 있으면 비모수 검정 우선 고려',
        generalPreserveOriginal: '원본 데이터도 보존하여 해석 시 참고',
        generalCLT: '표본 크기가 충분하면(n≥30) 중심극한정리 활용 가능',
      },
    },
    assumptions: {
      parametricAvailable: '모수적 검정 사용 가능',
      nonParametricRecommended: '비모수적 검정 권장',
      violationsFound: '발견된 가정 위반:',
      recommendedMethods: '권장 분석 방법:',
      violationKeywords: {
        normality: '정규성',
        homogeneity: '등분산',
        outlier: '이상치',
        sampleSize: '표본',
        etcSuffix: ' 등',
      },
      badges: {
        correlationAvailable: '상관분석 가능',
        groupComparisonAvailable: '그룹 비교 가능',
        regressionAvailable: '회귀분석 가능',
      },
      parametricMethods: {
        tTest: { name: 't-검정', description: '두 그룹 평균 비교' },
        anova: { name: 'ANOVA', description: '세 그룹 이상 평균 비교' },
        linearRegression: { name: '선형 회귀', description: '예측 및 관계 분석' },
      },
      nonParametricMethods: {
        mannWhitney: { name: 'Mann-Whitney U', description: 't-검정 대체' },
        kruskalWallis: { name: 'Kruskal-Wallis', description: 'ANOVA 대체' },
        spearman: { name: 'Spearman 상관', description: 'Pearson 대체' },
        robustRegression: { name: '로버스트 회귀', description: '이상치에 강건' },
      },
    },
    dataEditGuide: {
      title: '데이터 편집 가이드',
      introMessage: '통계 가정 충족을 위해 데이터를 변환하거나 편집해야 할 수 있습니다. 아래 방법들을 참고하여 데이터를 준비하세요.',
      warningMessage: '주의: 데이터 변환 전 원본을 반드시 백업하세요. 변환은 해석에 영향을 줄 수 있으므로 신중하게 선택하세요.',
      normality: {
        title: '정규성 문제 해결',
        methodsLabel: '변환 방법:',
        logTransform: '로그 변환: 오른쪽으로 치우친 데이터',
        sqrtTransform: '제곱근 변환: 약한 치우침',
        boxCoxTransform: 'Box-Cox 변환: 최적 람다 자동 결정',
      },
      outlierHandling: {
        title: '이상치 처리',
        methodsLabel: '처리 방법:',
        removal: '제거 (Removal):',
        winsorization: 'Winsorization:',
        iqrMethod: 'IQR 방법:',
      },
      missingValues: {
        title: '결측값 처리',
        methodsLabel: '대체 방법:',
        meanImputation: '평균 대체:',
        medianImputation: '중앙값 대체:',
        deletion: '삭제:',
      },
    },
    outlier: {
      title: '이상치 분석',
      detectionMethod: '탐지 방법',
      position: '위치',
      outlierValues: '이상치 값',
      noOutliers: '이상치가 발견되지 않았습니다',
      treatmentTitle: '처리 방법:',
      treatmentUnder5: '5% 미만: 그대로 진행 가능, 로버스트 통계 고려',
      treatment5to10: '5-10%: Winsorization, Trimming 고려',
      treatmentOver10: '10% 초과: 원인 파악 필수, 제거 또는 변환',
      outlierCount: (count: number, percent: number) => `${count}개 이상치 (${percent.toFixed(1)}%)`,
      lowerCount: (count: number) => `${count}개 하단`,
      upperCount: (count: number) => `${count}개 상단`,
      moreValues: (count: number) => ` ... 외 ${count}개`,
    },
    categorical: {
      title: '범주형 변수 빈도 분석',
      skewedDistribution: '편향 분포',
      sparseCategory: '희소 카테고리',
      emptyValue: '(빈 값)',
      noFrequencyInfo: '빈도 정보 없음',
      categoryCount: (count: number) => `${count}개 카테고리`,
      itemCount: (count: number) => `${count}개`,
      moreCategories: (count: number) => `... 외 ${count}개 카테고리`,
      missingCount: (count: number) => `결측값: ${count}개`,
    },
    additional: {
      title: '추가 기초 통계',
      labels: {
        quartileRange: '분위수 범위',
        iqr: 'IQR',
        range: '범위',
        standardError: '표준오차 (SE)',
        confidenceInterval: '95% CI',
      },
    },
  },

  validationSummary: {
    detailAnalysisTitle: (columnName: string) => `${columnName} 상세 분석`,
    chartTypes: { histogram: '히스토그램', boxplot: '박스플롯', ariaLabel: '차트 타입 선택' },
    histogramHoverTemplate: '%{x}: %{y}개<extra></extra>',
    heatmapHoverTemplate: '%{x} vs %{y}: %{z:.2f}<extra></extra>',
    axisLabels: { frequency: '빈도' },
    statistics: {
      mean: '평균', stdDev: '표준편차', minMax: '최소/최대', outliers: '이상치',
      meanLabel: '평균', stdDevLabel: '표준편차', modeLabel: '최빈값', frequencyLabel: '빈도',
    },
    outlierCount: (count: number) => `${count}개`,
    categoryFrequencyTitle: '카테고리별 빈도',
    mixedTypeMessage: '혼합 타입 변수는 시각화가 제한됩니다.',
    correlationTitle: '변수 간 상관관계',
    tableHeaders: {
      variableName: '변수명', type: '타입', missingValues: '결측값',
      uniqueValues: '고유값', statistics: '통계', actions: '작업',
    },
    typeLabels: { numeric: '숫자형', categorical: '범주형', mixed: '혼합' },
    viewDetailAriaLabel: (name: string) => `${name} 변수 상세 보기`,
    buttons: { view: '보기' },
    cardTitle: '데이터 검증 결과',
    errorCount: (count: number) => `${count}개 오류`,
    warningCount: (count: number) => `${count}개 경고`,
    statusNormal: '정상',
    summaryLabels: { totalRows: '총 행 수', totalColumns: '총 열 수', missingValues: '결측값', duplicateRows: '중복 행' },
    sectionLabels: { errors: '오류', warnings: '경고' },
    allPassedMessage: '모든 데이터 검증을 통과했습니다.',
  },

  resultsVisualization: {
    labels: { mean: '평균', sampleSize: '표본 크기', data: '데이터' },
    significantDifference: (pValue: string) => `통계적으로 유의한 차이가 있습니다 (p = ${pValue})`,
    groupComparison: { title: '그룹 간 평균 비교 (평균 ± 표준편차)' },
    correlation: { title: '상관관계 분석', coefficientLabel: '상관계수', determinationLabel: '결정계수' },
    regression: { title: '회귀분석 결과', independentVar: '독립변수', dependentVar: '종속변수', regressionLine: '회귀선', equationLabel: '회귀방정식' },
    nonparametric: { title: '비모수 검정 결과 (중위수/평균 ± 분산)', medianMean: '중위수/평균' },
    pca: {
      title: '분산 설명률', individualVariance: '개별 분산', cumulativeVariance: '누적 분산',
      noDataMessage: '분산 설명률 데이터가 없습니다.',
      summary: (componentCount: number, totalPercent: string) => `총 ${componentCount}개 주성분이 전체 분산의 ${totalPercent}%를 설명합니다.`,
    },
    cluster: { title: '군집 분석 결과', dimension1: '차원 1', dimension2: '차원 2', clusterCount: '군집 수' },
    reliability: {
      title: '항목-총점 상관', itemLabel: (index: number) => `항목 ${index}`,
      noDataMessage: '항목 상관 데이터가 없습니다.', acceptable: '수용 가능', low: '낮음',
    },
    power: { title: '검정력 곡선', powerLabel: '검정력', currentPower: '현재 검정력', requiredSampleSize: '필요 표본 크기' },
    fallback: {
      title: '분석 결과 시각화',
      preparing: (method: string) => `이 분석 유형(${method})에 대한 시각화를 준비 중입니다.`,
      seeBelow: '결과 데이터는 아래 섹션에서 확인할 수 있습니다.',
    },
    methodCategories: {
      test: '검정',
      correlation: '상관분석',
      regression: '회귀분석',
      nonparametric: '비모수 검정',
      pca: '주성분 분석',
      factor: '요인 분석',
      cluster: '군집 분석',
      kMeans: 'K-평균 군집',
      reliability: '신뢰도 분석',
      power: '검정력 분석',
    },
  },

  methodSpecificResults: {
    regression: {
      sectionTitle: '모델 적합도',
      rSquaredTooltip: '결정계수: 독립변수가 종속변수 분산의 몇 %를 설명하는지 나타냄',
      adjRSquaredTooltip: '수정 결정계수: 변수 수를 보정한 R²',
      rmseTooltip: '평균 제곱근 오차: 예측 정확도 (작을수록 좋음)',
      aicTooltip: '아카이케 정보 기준: 모델 선택 지표 (작을수록 좋음)',
      bicTooltip: '베이지안 정보 기준: 모델 선택 지표 (작을수록 좋음)',
      interceptLabel: '절편',
      interceptTooltip: '회귀 절편 (y-intercept)',
      vifWarningTitle: '다중공선성 경고',
      vifWarningMessage: (count: number) => `VIF > 5인 변수가 있습니다 (${count}개). 독립변수 간 상관이 높아 회귀계수 해석에 주의가 필요합니다.`,
    },
    classification: {
      sectionTitle: '분류 성능',
      accuracyLabel: '정확도', accuracyTooltip: '전체 예측 중 정확한 비율',
      precisionLabel: '정밀도', precisionTooltip: '양성 예측 중 실제 양성 비율',
      recallLabel: '재현율', recallTooltip: '실제 양성 중 양성으로 예측한 비율',
      f1Tooltip: '정밀도와 재현율의 조화평균',
      rocAucTooltip: 'ROC 곡선 아래 면적 (1에 가까울수록 좋음)',
      confusionMatrixLabel: '혼동행렬',
      predicted: (index: number) => `예측 ${index}`,
      actual: (index: number) => `실제 ${index}`,
    },
    pca: {
      sectionTitle: '주성분/요인 분석',
      varianceExplainedLabel: '분산 설명률', cumulativePrefix: '누적',
      eigenvalueLabel: (index: number) => `고유값 ${index}`,
      eigenvalueTooltip: (index: number, meetsKaiser: boolean) => `${index}번째 주성분/요인의 고유값${meetsKaiser ? ' (Kaiser 기준 충족)' : ''}`,
    },
    cluster: {
      sectionTitle: '군집 분석',
      silhouetteTooltip: '군집 품질 지표 (-1~1, 높을수록 잘 분리됨). 0.5+ 양호, 0.7+ 우수',
      dataCountLabel: '데이터 수', dataCountTooltip: '군집에 할당된 데이터 포인트 수',
      clusterCountLabel: '군집 수', clusterCountTooltip: '최종 결정된 군집 개수',
    },
    descriptive: {
      sectionTitle: '기술통계량',
      meanLabel: '평균', meanTooltip: '산술 평균',
      medianLabel: '중앙값', medianTooltip: '데이터를 크기순 정렬 시 중간값',
      stdDevLabel: '표준편차', stdDevTooltip: '데이터 산포도의 대표 지표',
      skewnessLabel: '왜도', skewnessTooltip: '분포의 비대칭 정도 (0이면 대칭)',
      kurtosisLabel: '첨도', kurtosisTooltip: '분포의 뾰족한 정도 (정규분포=3 기준)',
      sampleSizeLabel: '표본 크기', sampleSizeTooltip: '분석에 사용된 데이터 수',
    },
    reliability: {
      sectionTitle: '신뢰도 분석',
      alphaTooltip: '내적 일관성 신뢰도. 0.7+ 수용, 0.8+ 양호, 0.9+ 우수',
      itemCountLabel: '항목 수', itemCountTooltip: '신뢰도 분석에 포함된 항목 수',
    },
    power: {
      sectionTitle: '통계적 검정력',
      powerLabel: '검정력', powerTooltip: '실제 효과가 있을 때 이를 탐지할 확률. 0.8+ 권장',
      requiredSampleLabel: '필요 표본', requiredSampleTooltip: '목표 검정력 달성에 필요한 최소 표본 크기',
      analysisSampleLabel: '분석 표본', analysisSampleTooltip: '검정력 분석에 사용된 표본 크기',
    },
  },

  recommendedMethods: {
    smartRecommend: '스마트 추천 방법',
    hide: '숨기기', show: '보기',
    methodCount: (count: number) => `${count}개`,
    aiRecommendTitle: '데이터 기반 AI 추천',
    recommendedBadge: '추천',
    showBrief: '간략히 보기', showDetails: '자세히 보기',
    noDataProfile: '데이터 프로파일 정보가 없습니다',
    fitScoreDetails: '적합도 상세',
    sampleSize: (rows: number, minRequired: number) => `샘플 크기: ${rows}개 (최소 ${minRequired}개 필요)`,
    numericVars: (count: number) => `수치형 변수: ${count}개`,
    categoricalVars: (count: number) => `범주형 변수: ${count}개`,
    assumptionLabels: { normality: '정규성', homogeneity: '등분산성' },
    assumptionStatus: {
      needsCheck: '검정 필요', met: '충족',
      normalityFailed: '불충족 → 비모수 검정 권장',
      homogeneityFailed: '불충족 → Welch 검정 권장',
    },
  },

  conversationalQuestion: {
    aiAnalyzed: 'AI가 데이터를 분석했습니다',
    aiRecommendNeedsCheck: 'AI 추천 (확인 필요)',
    aiReferenceInfo: 'AI 참고 정보',
    recommendedBadge: '추천',
    keyboardHint: (optionCount: number) => `숫자 키(1-${optionCount})로 선택하거나 클릭하세요`,
  },

  variableMapping: {
    title: '변수 자동 매핑',
    editButton: '변수 매핑 편집',
    hideButton: '숨기기',
    roles: { dependent: '종속변수', independent: '독립변수', group: '그룹변수', time: '시간변수', variableList: '변수목록' },
    autoMappingHint: '자동 매핑은 기본값입니다. "변수 매핑 편집"을 눌러 독립/종속/그룹 변수를 확정하세요.',
  },

  questionFlowNav: {
    backToPurpose: '목적 선택으로',
    previous: '이전',
    restart: '처음부터',
    keyboardHint: 'Enter로 진행 · Esc로 취소',
    viewResults: '결과 확인',
    next: '다음',
  },

  reanalysis: {
    title: '재분석 모드',
    description: '이전 분석 설정을 새 데이터에 적용합니다',
    savedVariableSettings: '저장된 변수 설정',
    variableRoles: {
      dependentVar: '종속변수', independentVar: '독립변수', groupVar: '그룹변수',
      timeVar: '시간변수', variables: '분석변수', covariate: '공변량',
      within: '개체내 요인', between: '개체간 요인', blocking: '블록변수',
      event: '이벤트변수', censoring: '중도절단변수', weight: '가중치변수',
    },
    allVariablesMatch: '모든 변수가 일치합니다',
    matchedCount: (n: number) => `${n}개 변수 확인 완료.`,
    typeMismatchWarning: (n: number) => `타입 주의: ${n}개`,
    readyToAnalyze: '바로 분석할 수 있습니다.',
    typeCaution: '타입 주의사항:',
    analyzing: '분석 중...',
    runAnalysis: '분석 실행',
    variablesMismatch: '변수가 일치하지 않습니다',
    missingVariables: (required: number, missing: number) => `필요한 ${required}개 변수 중 ${missing}개가 없습니다.`,
    pleaseReselectVariables: '변수를 다시 선택해주세요.',
    editVariables: '변수 다시 선택',
    fixMappingFirst: '변수 매핑을 먼저 수정해주세요',
  },

  methodManager: {
    title: '통계 방법 관리',
    startAnalysis: (categoryTitle: string) => `${categoryTitle} 분석 시작`,
    notReady: '(준비중)',
  },

  chartLabels: {
    theoreticalNormal: '이론적 정규분포',
    theoreticalQuantile: '이론적 분위수',
    observedValue: '관측값',
    distributionTitle: (colName: string) => `분포: ${colName}`,
    value: '값',
    frequency: '빈도',
    errorMessage: '통계 검정 오류',
  },

  flowStateMachine: {
    evidencePrefix: (index: number) => `근거 ${index + 1}`,
    directSelection: '직접 선택',
    directSelectionDescription: '사용자가 직접 분석 방법을 선택했습니다',
  },

  decisionTree: {
    steps: {
      normality: '정규성',
      homogeneity: '등분산성',
      groupCount: '그룹 수',
      sampleType: '표본 유형',
      variableType: '변수 유형',
      comparisonTarget: '비교 대상',
      analysisType: '분석 유형',
      variableCount: '변수 수',
      predictorCount: '예측 변수 수',
      outcomeVariable: '결과 변수',
      modelType: '모형 유형',
      variableSelection: '변수 선택',
      designType: '설계 유형',
      dependentVariable: '종속변수',
      covariate: '공변량',
      analysisPurpose: '분석 목적',
      seasonality: '계절성',
      defaultStep: '기본',
    },
    descriptions: {
      singleSample: '단일 표본',
      twoGroupComparison: '2개 그룹 비교',
      threeOrMoreGroupComparison: '3개 이상 그룹 비교',
      pairedSample: '대응표본 (같은 대상 전/후)',
      independentSample: '독립표본 (서로 다른 대상)',
      sampleVsPopulation: '표본 vs 모집단',
      binaryProportionTest: '이진형 → 비율 검정',
      oneSampleTTest: '단일표본 t-검정',
      studentTTest: 'Student t-검정',
      repeatedMeasurement: '반복측정 (같은 대상 여러 시점)',
      binaryCochranQ: '이진 범주형 → Cochran Q 검정',
      binaryMcNemar: '이진 범주형 → McNemar 검정',
      independentGroup: '독립 그룹',
      mixedDesignMixedModel: '혼합 설계 → 혼합효과 모형',
      multivariateMANOVA: '다변량 → MANOVA',
      covariateANCOVA: '공변량 통제 → ANCOVA',
      oneWayANOVA: '일원분산분석',
      medianComparisonMood: '중앙값 비교 → Mood 검정',
      correlationAnalysis: '상관관계 분석',
      allNumeric: '모두 수치형',
      twoVariables: '2개 변수',
      threeOrMoreVariables: '3개 이상 변수',
      categoricalIncluded: '범주형 포함',
      predictionRegression: '예측/회귀 분석',
      simpleRegression: '단순 회귀',
      multipleRegression: '다중 회귀',
      categoricalLogistic: '범주형 포함 → 로지스틱 회귀',
      dataExploration: '데이터 탐색',
      meanVisualization: '평균 시각화',
      binaryProbabilityTest: '이진 확률 검정',
      randomnessTest: '무작위성 검정',
      twoDistributionComparison: '두 분포 비교',
      descriptiveStats: '기술통계',
      numericMeanStd: '수치형 → 평균, 표준편차 등',
      categoricalFreqRatio: '범주형 → 빈도, 비율',
      normalityTest: '정규성 검정',
      frequencyAnalysis: '빈도 분석',
      doseResponseAnalysis: '용량-반응 분석',
      optimizationExperiment: '최적화 실험',
      autoVariableStepwise: '자동 변수 선택 → 단계적 회귀',
      simpleModel: '단순 모형',
      multipleModel: '다중 모형',
      continuousLinearRegression: '연속형 → 선형 회귀',
      binaryLogisticRegression: '이진형 → 로지스틱 회귀',
      countPoissonRegression: '빈도/개수 → 포아송 회귀',
      multiclassMultinomialLogistic: '다범주 → 다항 로지스틱',
      ordinalOrdinalLogistic: '순서형 → 순서형 로지스틱',
      futureForecast: '미래 예측',
      seasonalSARIMA: '계절성 있음 → SARIMA',
      noSeasonalARIMA: '계절성 없음 → ARIMA',
      patternDecomposition: '패턴 분해',
      stationarityTest: '정상성 검정',
      trendTest: '추세 검정',
      timeseriesAnalysis: '시계열 분석',
      survivalCurveEstimation: '생존 곡선 추정',
      groupSurvivalComparison: '그룹 간 생존 비교',
      hazardFactorAnalysis: '위험 요인 분석',
      covariateYesCox: '공변량 있음 → Cox 회귀',
      covariateNone: '공변량 없음',
      dimensionReduction: '차원 축소',
      latentFactorExtraction: '잠재 요인 추출',
      similarGrouping: '유사 대상 그룹화',
      groupClassification: '그룹 분류/예측',
      multivariateAnalysis: '다변량 분석',
      sampleSizeCalculation: '표본 크기 계산',
      powerCalculation: '검정력 계산',
      reliabilityMeasurement: '측정 도구 신뢰도',
      utilityAnalysis: '유틸리티 분석',
      defaultDescriptive: '기본 기술통계 분석',
      proportionComparison: '비율 비교',
      normalMetParametric: '정규분포 충족 → 모수 검정',
      normalNotMetNonparametric: '정규분포 미충족 → 비모수 검정',
      normalMetPrefix: '정규분포 충족',
      normalNotMetPrefix: '정규분포 미충족',
      homoMet: '등분산 충족',
      homoMetPrefix: '등분산 충족',
      homoNotMetWelch: '등분산 미충족 → Welch 검정',
      homoUncheckedWelch: '등분산 미확인 → Welch 검정 (안전)',
    },
    reasons: {
      exactTestNeeded: '정확 검정이 필요할 때',
      signRankWhenNotNormal: '정규성 미충족시 부호순위 검정',
      cltRobustN30: 'n>=30이면 중심극한정리로 강건',
      cltRobustNPerGroup30: 'n/그룹>=30이면 강건',
      crosstabForm: '교차표 형태일 때',
      ordinalData: '순서형 데이터일 때',
      safeAlternativeUncertain: '정규성이 불확실할 때 안전한 대안',
      ordinalOrDirectional: '순서형 또는 방향성만 중요할 때',
      noEqualVarianceNeeded: '등분산 가정 없이도 사용 가능',
      nonparametricAlternative: '비모수 대안',
      equalVarianceConfirmed: '등분산 확인시 사용 가능',
      robustN30: 'n>=30이면 강건',
      twoTimepoints: '2시점만 비교할 때',
      sphericityViolated: '구형성 가정 위반시',
      simpleRepeatedMeasure: '단순 반복측정일 때',
      individualDVAnalysis: '종속변수 개별 분석시',
      covariateNotNeeded: '공변량 통제 불필요시',
      fullDistributionComparison: '분포 전체 비교시',
      medianComparisonPurpose: '중앙값 비교가 목적일 때',
      simpleCorrelation: '단순 상관 행렬',
      spearmanForOrdinal: '순서형 변수일 때 Spearman 사용',
      descriptiveOnly: '기술통계만 필요할 때',
      descriptiveTableAlternative: '기술통계표로 대체',
      largeApproximation: '대표본 근사 사용시',
      medianDifference: '중앙값 차이가 관심일 때',
      detailedExploration: '상세 탐색 필요시',
      comparisonDistribution: '비교 분포가 있을 때',
      expectedFrequency: '기대 빈도와 비교시',
      binaryRateTest: '이진 비율 검정시',
      explorationWithViz: '시각화 포함 탐색시',
      linearRelationship: '선형 관계 가정시',
      simplePrediction: '선형 추세 검정시',
      allVariablesIncluded: '모든 변수 포함시',
      variableSelectionNeeded: '변수 선택이 필요할 때',
      discriminantAlternative: '판별 분석 대안',
      ordinalCategory: '순서형 범주일 때',
      ignoreOrder: '순서 무시시',
      seasonalPatternAnalysis: '계절 패턴 분석 후 예측시',
      logRankForGroupComparison: '그룹 비교시 Log-rank 검정 옵션 사용',
      covariateControlNeeded: '공변량 통제가 필요할 때',
      addCovariate: '공변량 추가시',
      latentFactorInterpretation: '잠재 요인 해석이 필요할 때',
      dimensionReductionOnly: '차원 축소만 필요할 때',
      groupAlreadyDefined: '그룹이 이미 정의되어 있을 때',
      binaryClassification: '이진 분류일 때',
      groupNotDefined: '그룹이 정의되지 않았을 때',
    },
    warnings: {
      sphericity: '구형성 검정(Mauchly)을 확인하세요. 위반시 Greenhouse-Geisser 보정 적용',
      randomEffects: '랜덤효과 구조를 신중히 선택해야 합니다',
      multivariateNormality: '다변량 정규성, Box M 검정 확인 필요',
      regressionHomogeneity: '회귀 기울기 동질성 가정 확인 필요',
      spearmanOutliers: '정규성 미충족/이상치 존재시 Spearman 옵션 선택',
      doseResponseRange: 'EC50/IC50 계산에 충분한 농도 범위 필요',
      experimentalDesign: '실험 설계(CCD, BBD 등)가 적절해야 합니다',
      overfittingCrossValidation: '과적합 주의, 교차검증 권장',
      multicollinearity: '다중공선성(VIF), 잔차 정규성 확인 필요',
      rocAucHosmerLemeshow: 'ROC-AUC, Hosmer-Lemeshow 검정으로 적합도 확인',
      overdispersion: '과산포(overdispersion) 확인 - 있으면 음이항 회귀 고려',
      arimaSeasonalOption: 'ARIMA 페이지에서 계절성 옵션(SARIMA) 선택',
      kpssAdditional: 'KPSS 검정도 함께 수행하면 더 신뢰할 수 있습니다',
      autocorrelationModifiedMK: '자기상관이 있으면 Modified MK 사용 권장',
      proportionalHazards: '비례위험 가정 확인 필요 (Schoenfeld 잔차)',
      sampleSizePrereqs: '연구 설계, 효과 크기, 유의수준을 미리 정해야 합니다',
      minItemsRequired: '항목이 3개 이상 필요합니다',
    },
  },

  guidedQuestionData: {
    compare: [
      {
        id: 'comparison_target',
        required: true,
        question: '무엇을 비교하려고 하나요?',
        options: [
          { value: 'mean', label: '평균 비교', hint: '그룹 간 평균 차이 검정' },
          { value: 'proportion', label: '비율 비교', hint: '비율/백분율 차이 검정' },
          { value: 'median', label: '중앙값 비교', hint: '중앙값 차이 검정' },
          { value: 'population', label: '모집단 대비', hint: '표본 vs 알려진 모집단 값' },
        ],
      },
      {
        id: 'group_count',
        required: true,
        question: '비교할 그룹이 몇 개인가요?',
        options: [
          { value: '1', label: '1개 (모집단 비교)', hint: '예: 표본 평균 vs 기준값' },
          { value: '2', label: '2개 그룹', hint: '예: 처리군 vs 대조군' },
          { value: '3+', label: '3개 이상', hint: '예: A, B, C 양식장 비교' },
        ],
      },
      {
        id: 'sample_type',
        required: true,
        question: '표본은 어떤 유형인가요?',
        options: [
          { value: 'independent', label: '독립 표본', hint: '서로 다른 대상을 측정' },
          { value: 'paired', label: '대응 표본', hint: '같은 대상을 전/후 측정 또는 반복측정' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: '종속변수의 유형은?',
        options: [
          { value: 'continuous', label: '연속형 (수치)', hint: '체중, 길이, 농도 등' },
          { value: 'binary', label: '이진형 (예/아니오)', hint: '생존/폐사, 성공/실패' },
          { value: 'ordinal', label: '순서형', hint: '상/중/하, 등급' },
        ],
        autoAnswer: true,
      },
      {
        id: 'normality',
        required: false,
        question: '데이터가 정규분포를 따르나요?',
        options: [
          { value: 'yes', label: '예 (또는 n>=30)', hint: '모수 검정 가능' },
          { value: 'no', label: '아니오', hint: '비모수 검정 권장' },
          { value: 'check', label: '확인 필요', hint: 'AI가 데이터 검사' },
        ],
        autoAnswer: true,
      },
      {
        id: 'homogeneity',
        required: false,
        question: '그룹 간 분산이 동일한가요?',
        options: [
          { value: 'yes', label: '예 (등분산)', hint: 'Student t-test / 일반 ANOVA' },
          { value: 'no', label: '아니오 (이분산)', hint: 'Welch t-test / Welch ANOVA 권장' },
          { value: 'check', label: '확인 필요', hint: 'AI가 Levene 검정 결과 확인' },
        ],
        autoAnswer: true,
      },
      {
        id: 'has_covariate',
        required: false,
        question: '통제할 공변량(covariate)이 있나요?',
        options: [
          { value: 'no', label: '없음', hint: '일반 ANOVA' },
          { value: 'yes', label: '있음', hint: 'ANCOVA 고려' },
        ],
      },
      {
        id: 'outcome_count',
        required: false,
        question: '종속변수가 몇 개인가요?',
        options: [
          { value: '1', label: '1개', hint: '일반 ANOVA' },
          { value: '2+', label: '2개 이상', hint: 'MANOVA 고려' },
        ],
      },
      {
        id: 'design_type',
        required: false,
        question: '실험 설계 유형은?',
        options: [
          { value: 'simple', label: '단순 설계', hint: '하나의 독립변수' },
          { value: 'factorial', label: '요인 설계', hint: '여러 독립변수 (이원/삼원 ANOVA)' },
          { value: 'mixed', label: '혼합 설계', hint: '고정효과 + 랜덤효과' },
        ],
      },
    ] as GuidedQuestion[],
    relationship: [
      {
        id: 'relationship_type',
        required: true,
        question: '어떤 관계를 알고 싶으신가요?',
        options: [
          { value: 'correlation', label: '상관관계', hint: '두 변수가 함께 변하는지' },
          { value: 'prediction', label: '예측/인과', hint: 'X로 Y를 예측' },
        ],
      },
      {
        id: 'variable_count',
        required: true,
        question: '분석할 변수가 몇 개인가요?',
        options: [
          { value: '2', label: '2개', hint: '단순 상관/회귀' },
          { value: '3+', label: '3개 이상', hint: '다중 회귀/편상관' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: '변수 유형은 무엇인가요?',
        options: [
          { value: 'numeric', label: '모두 수치형', hint: 'Pearson/회귀' },
          { value: 'mixed', label: '범주형 포함', hint: '로지스틱/카이제곱' },
        ],
        autoAnswer: true,
      },
    ] as GuidedQuestion[],
    distribution: [
      {
        id: 'analysis_type',
        required: true,
        question: '어떤 분석을 원하시나요?',
        options: [
          { value: 'describe', label: '기술통계', hint: '평균, 표준편차, 분위수' },
          { value: 'normality', label: '정규성 검정', hint: '데이터 분포 확인' },
          { value: 'frequency', label: '빈도 분석', hint: '범주별 빈도/비율' },
          { value: 'explore', label: '데이터 탐색', hint: '시각화 포함 탐색' },
          { value: 'test_probability', label: '이항 확률 검정', hint: '성공 확률 검정' },
        ],
      },
      {
        id: 'distribution_goal',
        required: false,
        question: '구체적인 분석 목표는?',
        options: [
          { value: 'explore', label: '데이터 탐색', hint: '분포 확인' },
          { value: 'visualize_means', label: '평균 시각화', hint: '그룹별 평균 비교 그래프' },
          { value: 'test_probability', label: '확률 검정', hint: '이항 검정' },
          { value: 'randomness', label: '무작위성 검정', hint: '런 검정' },
          { value: 'distribution_compare', label: '분포 비교', hint: '두 분포가 같은지' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: '분석할 변수 유형은?',
        options: [
          { value: 'numeric', label: '수치형', hint: '연속형 데이터' },
          { value: 'categorical', label: '범주형', hint: '그룹/카테고리' },
        ],
        autoAnswer: true,
      },
    ] as GuidedQuestion[],
    prediction: [
      {
        id: 'outcome_type',
        required: true,
        question: '예측하려는 결과는 어떤 유형인가요?',
        options: [
          { value: 'continuous', label: '연속형 (수치)', hint: '선형 회귀' },
          { value: 'binary', label: '이진형 (예/아니오)', hint: '로지스틱 회귀' },
          { value: 'count', label: '빈도/개수', hint: '포아송 회귀' },
          { value: 'multiclass', label: '다범주', hint: '다항 로지스틱' },
          { value: 'ordinal', label: '순서형 범주', hint: '순서형 로지스틱' },
        ],
        autoAnswer: true,
      },
      {
        id: 'predictor_count',
        required: true,
        question: '예측 변수가 몇 개인가요?',
        options: [
          { value: '1', label: '1개', hint: '단순 회귀' },
          { value: '2+', label: '2개 이상', hint: '다중 회귀' },
        ],
        autoAnswer: true,
      },
      {
        id: 'variable_selection',
        required: false,
        question: '변수 선택 방법은?',
        options: [
          { value: 'manual', label: '직접 선택', hint: '모든 변수 포함' },
          { value: 'automatic', label: '자동 선택', hint: '단계적 회귀' },
        ],
      },
      {
        id: 'modelType',
        required: false,
        question: '특수한 모형 유형이 필요한가요?',
        options: [
          { value: 'standard', label: '표준 회귀', hint: '일반 선형/로지스틱' },
          { value: 'dose_response', label: '용량-반응', hint: 'EC50/IC50 곡선' },
          { value: 'optimization', label: '최적화 실험', hint: '반응표면 분석' },
        ],
      },
    ] as GuidedQuestion[],
    timeseries: [
      {
        id: 'goal',
        question: '시계열 분석의 목적은?',
        options: [
          { value: 'forecast', label: '미래 예측', hint: 'ARIMA, 지수평활' },
          { value: 'decompose', label: '패턴 분해', hint: '추세, 계절성 분리' },
          { value: 'stationarity', label: '정상성 검정', hint: 'ADF, KPSS 검정' },
          { value: 'trend_test', label: '추세 검정', hint: 'Mann-Kendall 검정' },
        ],
      },
      {
        id: 'seasonality',
        question: '계절성(주기적 패턴)이 있나요?',
        options: [
          { value: 'yes', label: '예', hint: '계절성 ARIMA (SARIMA)' },
          { value: 'no', label: '아니오', hint: '일반 ARIMA' },
          { value: 'unknown', label: '모름', hint: 'AI가 분석' },
        ],
        autoAnswer: true,
      },
    ] as GuidedQuestion[],
    survival: [
      {
        id: 'goal',
        question: '생존 분석의 목적은?',
        options: [
          { value: 'curve', label: '생존 곡선 추정', hint: 'Kaplan-Meier' },
          { value: 'hazard', label: '위험 요인 분석', hint: 'Cox 비례위험 회귀' },
          { value: 'compare', label: '그룹 간 생존 비교', hint: 'Log-rank 검정' },
        ],
      },
      {
        id: 'covariate_count',
        question: '공변량(위험 요인)이 있나요?',
        options: [
          { value: '0', label: '없음', hint: 'Kaplan-Meier 단독' },
          { value: '1+', label: '1개 이상', hint: 'Cox 회귀 고려' },
        ],
        autoAnswer: true,
      },
    ] as GuidedQuestion[],
    multivariate: [
      {
        id: 'goal',
        question: '다변량 분석의 목적은?',
        options: [
          { value: 'dimension_reduction', label: '차원 축소', hint: 'PCA - 변수 수 줄이기' },
          { value: 'latent_factors', label: '잠재 요인 추출', hint: '요인 분석 - 숨은 구조 파악' },
          { value: 'grouping', label: '유사 대상 그룹화', hint: '군집 분석 - 자동 분류' },
          { value: 'classification', label: '그룹 분류/예측', hint: '판별 분석 - 그룹 예측' },
        ],
      },
    ] as GuidedQuestion[],
    utility: [
      {
        id: 'goal',
        question: '무엇을 계산하려고 하나요?',
        options: [
          { value: 'sample_size', label: '필요 표본 크기', hint: '실험 전 표본수 계산' },
          { value: 'power', label: '검정력', hint: '현재 표본으로 효과 탐지 가능성' },
          { value: 'reliability', label: '측정 도구 신뢰도', hint: 'Cronbach α 등' },
        ],
      },
    ] as GuidedQuestion[],
  } as Record<string, GuidedQuestion[]>,

  progressiveCategoryData: [
    {
      id: 'compare',
      title: '차이/비교 분석',
      description: '그룹 간 차이를 검정하거나 전후 변화를 비교합니다',
      icon: 'GitCompare',
      subcategories: [
        {
          id: 'group-mean',
          title: '그룹 간 평균 비교',
          description: '두 개 이상 그룹의 평균 차이를 검정합니다',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'mean',
          },
        },
        {
          id: 'pre-post',
          title: '전/후 변화 비교',
          description: '같은 대상의 시점 간 변화를 분석합니다',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'mean',
            sample_type: 'paired',
            group_count: '2',
          },
        },
        {
          id: 'proportion',
          title: '비율 비교',
          description: '그룹 간 비율이나 빈도의 차이를 검정합니다',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'proportion',
            variable_type: 'binary',
          },
        },
        {
          id: 'distribution',
          title: '분포/빈도 분석',
          description: '데이터의 분포 형태나 범주별 빈도를 분석합니다',
          mapsToPurpose: 'distribution',
        },
      ],
    },
    {
      id: 'relationship',
      title: '관계 분석',
      description: '변수 간의 상관관계나 연관성을 분석합니다',
      icon: 'TrendingUp',
      subcategories: [
        {
          id: 'correlation',
          title: '상관관계 분석',
          description: '두 개 이상 수치형 변수 간의 관계를 분석합니다',
          mapsToPurpose: 'relationship',
          presetAnswers: {
            relationship_type: 'correlation',
          },
        },
        {
          id: 'categorical-association',
          title: '범주형 연관 분석',
          description: '범주형 변수 간의 연관성을 분석합니다 (카이제곱 등)',
          mapsToPurpose: 'relationship',
          presetAnswers: {
            variable_type: 'categorical',
          },
        },
      ],
    },
    {
      id: 'prediction',
      title: '예측 분석',
      description: '독립변수로 종속변수를 예측하는 모델을 만듭니다',
      icon: 'LineChart',
      subcategories: [
        {
          id: 'regression',
          title: '수치 예측 (회귀)',
          description: '연속형 종속변수를 예측합니다',
          mapsToPurpose: 'prediction',
          presetAnswers: {
            outcome_type: 'continuous',
          },
        },
        {
          id: 'classification',
          title: '분류 예측',
          description: '범주형 종속변수를 예측합니다 (로지스틱 회귀 등)',
          mapsToPurpose: 'prediction',
          presetAnswers: {
            outcome_type: 'binary',
          },
        },
      ],
    },
    {
      id: 'advanced',
      title: '고급 분석',
      description: '시계열, 생존분석, 다변량 분석 등 전문 분석을 수행합니다',
      icon: 'Layers',
      subcategories: [
        {
          id: 'timeseries',
          title: '시계열 분석',
          description: '시간에 따른 데이터 패턴을 분석하고 예측합니다',
          mapsToPurpose: 'timeseries',
        },
        {
          id: 'survival',
          title: '생존 분석',
          description: '사건 발생까지의 시간을 분석합니다',
          mapsToPurpose: 'survival',
        },
        {
          id: 'multivariate',
          title: '다변량 분석',
          description: 'PCA, 요인분석, 군집분석 등을 수행합니다',
          mapsToPurpose: 'multivariate',
        },
        {
          id: 'utility',
          title: '연구 설계 도구',
          description: '표본 크기 계산, 검정력 분석, 신뢰도 분석 등',
          mapsToPurpose: 'utility',
        },
      ],
    },
  ] as CategoryDefinition[],

  autoAnswerEvidence: {
    normality: {
      cltGroupSize: (size: number) => `추정 최소 그룹 크기 ≈ ${size} ≥ 30 (CLT 적용 가능, 확인 권장)`,
      cltSampleSize: (n: number) => `n=${n} ≥ 30 (중심극한정리에 의해 정규성 가정 가능)`,
      noTestResult: '정규성 검정 결과가 없습니다',
      shapiroNormal: (pValueStr: string) => `Shapiro-Wilk p=${pValueStr} > 0.05 (정규분포 충족)`,
      shapiroNotNormal: (pValueStr: string) => `Shapiro-Wilk p=${pValueStr} ≤ 0.05 (정규분포 미충족)`,
      allGroupsNormal: '모든 그룹이 정규분포를 따릅니다',
      someGroupsNotNormal: '일부 그룹이 정규분포를 따르지 않습니다',
      cannotDetermine: '정규성을 확인할 수 없습니다',
    },
    variableType: {
      noInfo: '변수 정보가 없습니다',
      allNumeric: (count: number) => `분석 변수가 모두 수치형입니다 (${count}개)`,
      includesCategorical: '범주형 변수가 포함되어 있습니다',
      pleaseCheck: '변수 유형을 확인해주세요',
    },
    outcomeType: {
      noDependentSelected: '종속 변수가 선택되지 않았습니다',
      dependentNotFound: '종속 변수 정보를 찾을 수 없습니다',
      binaryVariable: (name: string) => `${name}은 2개 범주를 가진 이진 변수입니다`,
      multiclassVariable: (name: string, count: number) => `${name}은 ${count}개 범주를 가집니다`,
      possibleCountData: (name: string) => `${name}이 빈도/개수 데이터일 수 있습니다`,
      continuousVariable: (name: string) => `${name}은 연속형 수치 변수입니다`,
      pleaseCheckOutcome: '결과 변수 유형을 확인해주세요',
    },
    predictorCount: {
      noIndependentSelected: '독립 변수가 선택되지 않았습니다',
      onePredictor: '1개의 예측 변수가 선택되었습니다',
      multiplePredictors: (count: number) => `${count}개의 예측 변수가 선택되었습니다`,
    },
    covariateCount: {
      noCovariateSelected: '공변량이 선택되지 않았습니다',
      covariatesSelected: (count: number) => `${count}개의 공변량이 선택되었습니다`,
    },
    homogeneity: {
      noTestResult: '등분산성 검정 결과가 없습니다',
      leveneNoP: 'Levene 검정 결과 있음 (p-value 정보 없음)',
      leveneEqual: (pValueStr: string) => `Levene p=${pValueStr} > 0.05 (등분산 충족)`,
      leveneNotEqual: (pValueStr: string) => `Levene p=${pValueStr} ≤ 0.05 (등분산 미충족 → Welch 권장)`,
      bartlettNoP: 'Bartlett 검정 결과 있음 (p-value 정보 없음)',
      bartlettEqual: (pValueStr: string) => `Bartlett p=${pValueStr} > 0.05 (등분산 충족)`,
      bartlettNotEqual: (pValueStr: string) => `Bartlett p=${pValueStr} ≤ 0.05 (등분산 미충족 → Welch 권장)`,
      cannotDetermine: '등분산성을 확인할 수 없습니다',
    },
    seasonality: {
      needsAnalysis: '계절성은 데이터를 분석해야 확인할 수 있습니다',
    },
  },
}
