/**
 * Generic Statistical Terminology
 *
 * 범용 통계 용어 사전
 * - 도메인에 구애받지 않는 일반적인 통계 용어
 */

import type { TerminologyDictionary } from '../terminology-types'

export const generic: TerminologyDictionary = {
  domain: 'generic',
  displayName: '범용 통계',

  variables: {
    group: {
      title: 'Group Variable',
      description: 'Categorical variable defining groups to compare',
      shortLabel: 'Group'
    },
    dependent: {
      title: 'Dependent Variable (Y)',
      description: 'Numeric variable to compare across groups',
      shortLabel: 'Dependent'
    },
    independent: {
      title: 'Independent Variable (X)',
      description: 'Predictor variables',
      shortLabel: 'Independent'
    },
    factor: {
      title: 'Factor',
      description: 'Categorical factor variable',
      shortLabel: 'Factor'
    },
    covariate: {
      title: 'Covariate',
      description: 'Continuous control variable',
      shortLabel: 'Covariate'
    },
    time: {
      title: 'Time Variable',
      description: 'Time or sequence variable',
      shortLabel: 'Time'
    },
    event: {
      title: 'Event Variable',
      description: 'Binary outcome variable',
      shortLabel: 'Event'
    },
    pairedFirst: {
      title: 'Time 1 / Before',
      description: 'First measurement',
      shortLabel: 'Before'
    },
    pairedSecond: {
      title: 'Time 2 / After',
      description: 'Second measurement',
      shortLabel: 'After'
    },
    correlation: {
      title: 'Numeric Variables',
      description: 'Select 2 or more numeric variables to analyze correlations',
      shortLabel: 'Variables'
    }
  },

  validation: {
    groupRequired: 'Group variable is required',
    dependentRequired: 'Dependent variable is required',
    independentRequired: 'Independent variable is required',
    factorRequired: 'Factor is required',
    twoGroupsRequired: (current: number) =>
      `t-test requires exactly 2 groups (found ${current})`,
    minVariablesRequired: (min: number) =>
      `At least ${min} variable(s) required`,
    maxVariablesExceeded: (max: number) =>
      `Maximum ${max} variables allowed`,
    differentVariablesRequired: 'Please select two different variables',
    noNumericVariables: 'No numeric variables found',
    noCategoricalVariables: 'No categorical variables found'
  },

  success: {
    allVariablesSelected: 'All variables selected. Ready for analysis.',
    readyForAnalysis: 'Ready for analysis',
    variablesSelected: (count: number) =>
      `${count} variables selected. Ready for correlation analysis.`,
    correlationPairsCount: (count: number) =>
      `Will generate ${count} correlation pairs`,
    modelReady: (type: 'simple' | 'multiple', predictors: number) =>
      `${type === 'simple' ? 'Simple' : 'Multiple'} regression model ready. ${predictors} predictor(s) selected.`
  },

  selectorUI: {
    titles: {
      groupComparison: 'Group Comparison Variable Selection',
      oneSample: 'One-Sample Test Variable Selection',
      paired: 'Paired Samples Variable Selection',
      correlation: 'Correlation Variable Selection',
      multipleRegression: 'Multiple Regression Variable Selection',
      twoWayAnova: 'Two-way ANOVA Variable Selection'
    },
    descriptions: {
      groupComparison: 'Select a group variable and a dependent variable to compare',
      oneSample: 'Select a test variable and reference value',
      paired: 'Select two related measurements to compare (e.g., before/after)',
      correlation: 'Select 2 or more numeric variables to analyze correlations',
      multipleRegression: 'Select dependent (Y) and independent (X) variables',
      twoWayAnova: 'Select 2 categorical factors and 1 dependent variable'
    },
    buttons: {
      back: 'Back',
      runAnalysis: 'Run Analysis',
      selectAll: 'Select All',
      clear: 'Clear',
      swap: 'Swap'
    },
    labels: {
      selected: 'Selected',
      compare: 'Compare:',
      across: 'across',
      model: 'Model:',
      levels: 'levels',
      groups: 'groups',
      numeric: 'numeric',
      range: 'Range',
      mean: 'Mean'
    }
  },

  smartFlow: {
    stepTitles: {
      dataUpload: 'Data Upload',
      dataExploration: 'Data Exploration',
      purposeInput: 'Method Selection',
      variableSelection: 'Variable Selection',
      analysisExecution: 'Run Analysis',
      results: 'Results'
    },
    stepShortLabels: {
      exploration: 'Explore',
      method: 'Method',
      variable: 'Variables',
      analysis: 'Analyze'
    },
    statusMessages: {
      analyzing: 'Analyzing data...',
      analysisComplete: 'Analysis complete',
      uploadingData: 'Uploading data...',
      validatingData: 'Validating data...'
    },
    emptyStates: {
      dataRequired: 'Data Required',
      dataRequiredDescription: 'Please upload your data first.',
    },
    aiVariables: {
      title: 'AI Recommended Variables',
      roles: {
        dependent: 'Dependent:',
        group: 'Group:',
        factors: 'Factors:',
        independent: 'Independent:',
        covariate: 'Covariate:',
      },
    },
    floatingNav: {
      toMethod: 'Select Method',
      toVariables: 'Select Variables',
      toExecution: 'Run Analysis',
      runAnalysis: 'Run Analysis',
      defaultNext: 'Next Step',
    },
    errors: {
      uploadFailed: (message: string) => `Error uploading data: ${message}`,
      retryLabel: 'Retry',
    },
    modeBanners: {
      reanalysis: {
        description: 'Analyze new data with previous settings. Upload data below.',
      },
      quickAnalysis: {
        badge: 'Quick Analysis',
        description: 'Upload data to go directly to variable selection.',
        normalMode: 'Normal Mode',
        changeMethod: 'Change Method',
      },
    },
    buttons: {
      runAnalysis: 'Run Analysis',
      reanalyze: 'Reanalyze with Different Data',
      downloadResults: 'Download Results',
      backToHub: 'Back to Hub'
    },
    resultSections: {
      effectSizeDetail: 'Effect Size Details'
    },
    executionStages: {
      prepare: { label: 'Preparing environment', message: 'Preparing analysis environment...' },
      preprocess: { label: 'Data preprocessing', message: 'Preprocessing data...' },
      assumptions: { label: 'Assumption testing', message: 'Testing statistical assumptions...' },
      analysis: { label: 'Statistical analysis', message: 'Running statistical analysis...' },
      additional: { label: 'Additional statistics', message: 'Computing additional statistics...' },
      finalize: { label: 'Finalizing results', message: 'Finalizing results...' }
    },
    layout: {
      appTitle: 'NIFS Statistics',
      historyTitle: 'Analysis History',
      historyClose: 'Close history',
      historyCount: (n: number) => `History (${n})`,
      aiChatbot: 'AI Chatbot',
      helpLabel: 'Help',
      settingsLabel: 'Settings',
      nextStep: 'Next Step',
      analyzingDefault: 'Analyzing...',
      dataSizeGuide: 'Data Size Guide',
      currentLimits: 'Current Limits',
      memoryRecommendation: 'Recommended by Memory',
      detectedMemory: (gb: number) => `→ Detected memory: ${gb}GB`,
      limitFileSize: 'Max file: 50MB',
      limitDataSize: 'Max data: 100,000 rows × 1,000 columns',
      limitRecommended: 'Recommended: under 10,000 rows',
      memoryTier4GB: '4GB RAM: ~10,000 rows',
      memoryTier8GB: '8GB RAM: ~30,000 rows',
      memoryTier16GB: '16GB RAM: ~60,000 rows',
      stepTooltip: (stepName: string) => `Go to ${stepName} step`,
    },
    execution: {
      runningTitle: 'Running Analysis',
      resumeButton: 'Resume',
      pauseButton: 'Pause',
      cancelButton: 'Cancel',
      pauseDisabledTooltip: 'Cannot pause after 75%',
      cancelConfirm: 'Are you sure you want to cancel?\nResults computed so far will not be saved.',
      logSectionLabel: (n: number) => `Execution log (${n} entries)`,
      noLogs: 'No logs available',
      dataRequired: 'Required data or method has not been selected.',
      unknownError: 'An unknown error occurred',
      estimatedTimeRemaining: (seconds: number) => `Estimated time remaining: ${seconds}s`,
    },
    executionLogs: {
      stageStart: (label: string) => `${label} started`,
      engineReadyCached: 'Statistics engine ready (cached)',
      engineLoading: 'Loading statistics engine... (3-5 seconds)',
      engineReady: 'Statistics engine ready',
      dataLoaded: (n: number) => `Data loaded (n=${n})`,
      missingHandled: (count: number) => `Missing values handled (removed: ${count})`,
      normalityTestStart: 'Normality test (Shapiro-Wilk) starting...',
      normalityTestDone: (p: string) => `Normality test complete (p=${p})`,
      normalityTestFailed: 'Normality test failed (insufficient data or error)',
      homogeneityTestStart: 'Homogeneity test (Levene) starting...',
      homogeneityTestDone: (p: string) => `Homogeneity test complete (p=${p})`,
      homogeneityTestFailed: 'Homogeneity test failed (insufficient data or error)',
      assumptionSkipped: 'Assumption tests skipped (conditions not met)',
      methodExecuting: (name: string) => `Executing ${name}`,
      aiSettingsApplied: (alpha: number) => `AI suggested settings applied: α=${alpha}`,
      aiPostHoc: (method: string) => `ℹ️ AI suggested post-hoc: ${method} (planned for future)`,
      aiAlternative: (direction: string) => `ℹ️ AI suggested test direction: ${direction} (planned for future)`,
      effectSizeDone: 'Effect size calculation complete',
      confidenceIntervalDone: 'Confidence interval calculation complete',
      analysisDone: 'Analysis complete!',
      totalTime: (seconds: string) => `Total time: ${seconds}s`,
      errorPrefix: (message: string) => `❌ Error: ${message}`,
      userCancelled: 'Analysis cancelled by user',
      locale: 'en-US',
    },
  },

  purposeInput: {
    purposes: {
      compare: {
        title: 'Group Comparison',
        description: 'Compare means or proportions across two or more groups.',
        examples: 'e.g., Compare growth rates across farms, weight gain by feed type, temperature by region'
      },
      relationship: {
        title: 'Variable Relationships',
        description: 'Analyze correlations and associations between two or more variables.',
        examples: 'e.g., Relationship between temperature and growth, correlation between height and weight'
      },
      distribution: {
        title: 'Distribution & Frequency',
        description: 'Examine data distributions and analyze categorical frequencies.',
        examples: 'e.g., Distribution of body length, proportion by category, density distribution by area'
      },
      prediction: {
        title: 'Predictive Modeling',
        description: 'Build models to predict outcomes using independent variables.',
        examples: 'e.g., Predict yield from temperature, predict growth from feed amount'
      },
      timeseries: {
        title: 'Time Series Analysis',
        description: 'Analyze temporal patterns and forecast future values.',
        examples: 'e.g., Monthly yield trends, yearly production changes, seasonal temperature patterns'
      },
      survival: {
        title: 'Survival Analysis',
        description: 'Analyze time-to-event data and identify risk factors.',
        examples: 'e.g., Survival duration, facility lifespan, time from disease onset to outcome'
      },
      multivariate: {
        title: 'Multivariate Analysis',
        description: 'Analyze multiple variables simultaneously for dimension reduction, factor extraction, or clustering.',
        examples: 'e.g., PCA for indicators, cluster analysis for grouping, discriminant analysis for classification'
      },
      utility: {
        title: 'Research Design Tools',
        description: 'Calculate sample sizes, power analysis, and reliability assessment.',
        examples: 'e.g., Required sample size, Cronbach α reliability, power analysis'
      }
    },
    inputModes: {
      aiRecommend: 'AI Recommend',
      directSelect: 'Browse All',
      modeAriaLabel: 'Analysis method selection mode'
    },
    buttons: {
      back: 'Back',
      allMethods: 'All Methods',
      useThisMethod: 'Use This Method'
    },
    labels: {
      selectionPrefix: 'Selected:',
      directBadge: 'Manual',
      purposeHeading: 'What analysis would you like to perform?'
    },
    messages: {
      purposeHelp: 'Select one of the 8 analysis purposes. Guided questions will help recommend the best statistical method.',
      guidanceAlert: 'Select an analysis purpose above to get step-by-step guidance for choosing the optimal statistical method.',
      aiRecommendError: 'Failed to generate recommendation. Please try again.',
      genericError: 'An error occurred. Please try again.',
    },
    aiLabels: {
      recommendTitle: 'AI Recommended Analysis',
    },
  },

  fitScore: {
    levels: {
      excellent: { label: 'Excellent Fit', shortLabel: 'Optimal', description: 'Highly suitable for your data' },
      good: { label: 'Good Fit', shortLabel: 'Good', description: 'Works well with your data' },
      caution: { label: 'Use with Caution', shortLabel: 'Caution', description: 'Some conditions are not met' },
      poor: { label: 'Poor Fit', shortLabel: 'Poor', description: 'Consider alternative methods' },
      unknown: { label: 'Cannot Evaluate', shortLabel: 'Unknown', description: 'Insufficient data information' },
    },
    confidenceLabel: 'Confidence',
  },

  analysisInfo: {
    cardTitle: 'Analysis Info',
    labels: {
      fileName: 'File Name',
      dataSize: 'Data Size',
      method: 'Method',
      analysisTime: 'Analysis Time',
      dataQuality: 'Data Quality',
      assumptions: 'Assumption Tests',
      variables: 'Variable Configuration',
    },
    variableRoles: {
      dependent: 'Dependent',
      independent: 'Independent',
      group: 'Group',
      factor: 'Factor',
      paired: 'Paired',
    },
    dataQuality: {
      missingValues: (count: number, percent: string) => `${count} missing values (${percent}%)`,
      duplicateRows: (count: number) => `${count} duplicate rows`,
      warnings: (count: number) => `${count} warning(s)`,
    },
    assumptions: {
      normality: 'Normality',
      homogeneity: 'Homogeneity',
      independence: 'Independence',
      met: 'Met',
      partialViolation: 'Partial Violation',
      allGroupsNormal: 'All groups normal',
      someGroupsNonNormal: 'Some groups non-normal',
    },
    units: {
      rows: 'rows',
      nVariables: (count: number) => `${count} variables`,
    },
  },

  history: {
    empty: {
      title: 'No analysis history',
      description: 'Completed analyses are automatically saved',
    },
    recordCount: (n: number) => `${n} records`,
    buttons: {
      saveCurrent: 'Save Current Analysis',
      clearAll: 'Clear All',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
    },
    labels: {
      filterByMethod: 'Filter by Method',
      showAll: 'Show All',
      searchPlaceholder: 'Search history...',
      noMethod: 'No method',
      noPurpose: 'No purpose',
      current: 'Current',
      rows: 'rows',
      pValue: 'p-value:',
      effectSize: 'Effect size:',
    },
    tooltips: {
      viewResults: 'View saved results',
      reanalyze: 'Analyze new data with this method',
      delete: 'Delete',
    },
    dialogs: {
      deleteTitle: 'Delete Analysis History',
      deleteDescription: 'Are you sure you want to delete this analysis history? This action cannot be undone.',
      clearTitle: 'Clear All History',
      clearDescription: (count: number) => `Delete all ${count} analysis history records?\nThis action cannot be undone.`,
      saveTitle: 'Save Current Analysis',
      saveDescription: 'Name and save the current analysis.',
      analysisName: 'Analysis Name',
      savePlaceholder: 'e.g., 2024 Experiment Data T-test',
    },
  },

  hub: {
    hero: {
      heading: 'From data to insight,',
      subheading: 'scientifically.',
      description: 'Upload CSV or Excel files and AI will analyze your data characteristics and recommend the optimal statistical method. Expert-level analysis in just a few clicks.',
      statMethods: (count: number) => `${count} analysis tools`,
      statCategories: (count: number) => `${count} categories`,
      statAi: 'AI Recommend',
      uploadButton: 'Start with Data Upload',
      browseButton: 'Browse Methods',
    },
    chatInput: {
      heading: 'What would you like to analyze?',
      placeholder: 'Describe what you want to analyze...',
      sendAriaLabel: 'Send',
      processingMessage: 'Figuring out the best approach...',
    },
    tracks: {
      directAnalysis: {
        title: 'Direct Analysis',
        description: 'Start right away if you know the method',
        example: 'I want to run a t-test',
      },
      dataConsultation: {
        title: 'Data Consultation',
        description: 'Upload data and consult with AI for analysis',
        example: 'Help me figure out which analysis to use',
      },
      experimentDesign: {
        title: 'Experiment Design',
        description: 'Plan experiments, sample size, and power analysis',
        example: 'What sample size do I need?',
      },
    },
    experimentNotReady: 'Experiment design is coming soon. Redirecting to data consultation.',
    cards: {
      methodsTitle: 'Analysis Tools',
      methodsDescription: (categories: number) => `Browse T-test, ANOVA, Regression and more across ${categories} categories`,
      methodsLink: 'Explore',
      aiTitle: 'AI Recommend',
      aiDescription: 'Describe your analysis goal in natural language and get optimal method recommendations for your data',
      aiLink: 'Get Started',
      recentTitle: 'Recent Analyses',
      viewAll: 'View All',
      historyLabel: 'History',
      unknownMethod: 'Unknown',
      emptyTitle: 'No analysis records yet',
      emptyDescription: 'Start your first analysis',
    },
    quickAnalysis: {
      title: 'Quick Analysis',
      emptyPlaceholder: 'Add via edit',
      editTooltip: 'Edit quick analysis',
      editButton: 'Edit',
      frequentlyUsed: 'Frequently used:',
    },
    aiSearch: {
      title: 'AI Analysis Guide',
      description: 'Describe your research goal or hypothesis and get statistical method recommendations.',
      placeholder: 'e.g., "Compare means between two groups" or "Find the relationship between A and B"',
      sendButton: 'Analyze',
      startButton: 'Get Started',
      alternatives: (count: number) => `${count} more alternatives`,
      detailedLink: 'Detailed Mode',
      recommendationBadge: 'Recommended',
      selectButton: 'Select'
    },
    editDialog: {
      title: 'Edit Quick Analysis',
      selectedCount: (count: number) => `${count} selected`,
      cancel: 'Cancel',
      save: 'Save',
    },
    timeAgo: {
      justNow: 'Just now',
      minutesAgo: (n: number) => `${n}m ago`,
      hoursAgo: (n: number) => `${n}h ago`,
      daysAgo: (n: number) => `${n}d ago`,
    },
    categoryLabels: {
      't-test': 'T-Test',
      'anova': 'ANOVA',
      'nonparametric': 'Nonparametric',
      'correlation': 'Correlation',
      'regression': 'Regression',
      'chi-square': 'Categorical',
      'descriptive': 'Descriptive',
      'timeseries': 'Time Series',
      'survival': 'Survival',
      'pca': 'Dimension Reduction',
      'clustering': 'Clustering',
      'advanced': 'Advanced',
      'design': 'Experimental Design',
      'psychometrics': 'Psychometrics',
    },
    entryPoints: {
      dataUpload: 'Data Upload',
      aiRecommend: 'AI Recommend',
      methodSelect: 'Select Method',
      history: 'History',
    },
    quickMethodNames: {
      't-test': 'T-Test', 'anova': 'ANOVA', 'correlation': 'Correlation',
      'regression': 'Regression', 'chi-square': 'Chi-Square',
      'paired-t-test': 'Paired T-Test', 'mann-whitney': 'Mann-Whitney U',
      'wilcoxon': 'Wilcoxon', 'kruskal-wallis': 'Kruskal-Wallis',
      'fisher-exact': 'Fisher Exact Test',
    },
  },

  guidedQuestions: {
    assumptionLabels: {
      normality: 'Normality',
      homogeneity: 'Homogeneity',
    },
    assumptionStatus: {
      met: 'Met',
      violated: 'Violated',
      needsCheck: 'Needs Check',
    },
    badges: {
      manualOverride: 'Manual Override',
    },
    buttons: {
      modify: 'Modify',
      autoApply: 'Auto Apply',
      browseAll: 'Browse all methods',
      directSelect: 'Direct Select',
      back: 'Back',
      next: 'Next',
      close: 'Close',
      collapse: 'Collapse',
      expand: 'Expand',
    },
    tooltips: {
      switchToClassic: 'Switch to classic mode',
      switchToConversational: 'Switch to conversational mode',
    },
    sections: {
      assumptionResults: 'Assumption Test Results',
      advancedOptions: 'Advanced Options',
    },
    card: {
      title: 'Tell us about your data',
      description: 'Answer a few questions for accurate method recommendation',
    },
  },

  dataExploration: {
    empty: {
      title: 'Upload data to get started',
      description: 'Upload a CSV or Excel file to automatically perform data summary, distribution visualization, and correlation analysis.',
    },
    features: {
      descriptiveTitle: 'Descriptive Statistics',
      descriptiveDesc: 'Mean, standard deviation, quartiles, skewness/kurtosis, etc.',
      distributionTitle: 'Distribution Visualization',
      distributionDesc: 'Histograms, box plots, outlier detection',
      correlationTitle: 'Correlation Analysis',
      correlationDesc: 'Scatter plots, correlation heatmaps, trend lines',
    },
    tabs: {
      dataSummary: 'Data Summary',
      fullDataView: (n: number) => `View All Data (${n} rows)`,
      statistics: 'Descriptive Statistics',
      preview: 'Data Preview',
    },
    headers: {
      variableName: 'Variable',
      count: 'N',
      mean: 'Mean',
      stdDev: 'Std Dev',
      median: 'Median',
      min: 'Min',
      max: 'Max',
      skewness: 'Skewness',
      kurtosis: 'Kurtosis',
      outliers: 'Outliers',
    },
    interpretGuide: {
      title: 'Interpretation Guide:',
      skewness: 'Skewness: |value| > 2 → severe asymmetry (⚠)',
      kurtosis: 'Kurtosis: |value| > 7 → many extreme values (⚠)',
      outlierDef: 'Outliers: values beyond IQR × 1.5 range',
      nDef: 'N: count of valid values (excluding missing)',
    },
    outlier: {
      detected: (varCount: number, totalCount: number) => `Outliers detected: ${totalCount} found across ${varCount} variables`,
      variableDetail: (name: string, count: number) => `${name}(${count})`,
      moreVars: (count: number) => `and ${count} more variables`,
      count: (n: number) => `${n}`,
      info: (count: number, lower: string, upper: string) => `Outliers: ${count} found (range: <${lower} or >${upper})`,
    },
    chartTypes: {
      histogram: 'Histogram',
      boxplot: 'Box Plot',
      ariaLabel: 'Chart type selection',
    },
    distribution: {
      title: 'Data Distribution Visualization',
      description: 'Explore distributions of numeric variables via histograms or box plots',
    },
    histogram: {
      title: (varName: string) => `${varName} Distribution`,
      yAxisLabel: 'Frequency',
    },
    boxplot: {
      selectInstruction: 'Click variables to compare (up to 8)',
      singleTitle: (varName: string) => `${varName} Box Plot`,
      multipleTitle: (count: number) => `Variable Distribution Comparison (${count})`,
    },
    scatterTabs: {
      scatter: 'Scatter Plot',
      heatmap: 'Correlation Heatmap',
    },
    scatter: {
      variableRelation: 'Variable Relationship Analysis',
      xAxis: 'X-axis (Independent)',
      yAxis: 'Y-axis (Dependent)',
    },
    correlation: {
      coefficient: 'Correlation',
      determination: 'R²',
      strong: 'Strong correlation',
      medium: 'Moderate correlation',
      weak: 'Weak correlation',
    },
    heatmap: {
      title: 'Correlation Heatmap',
      description: 'Visualizes correlations between all numeric variable pairs',
      calculating: 'Calculating correlations...',
      variableCount: (n: number) => `Analyzing ${n} variables`,
    },
    heatmapGuide: {
      title: 'Interpreting Correlations:',
      strongPositive: 'r = +1: Strong positive correlation',
      strongNegative: 'r = -1: Strong negative correlation',
      noCorrelation: 'r = 0: No correlation',
      veryStrong: '|r| >= 0.7: Very strong correlation',
    },
    strongCorrelations: {
      title: 'Key Correlations (|r| >= 0.5)',
    },
    strength: {
      weak: 'Weak',
      medium: 'Moderate',
      strong: 'Strong',
      veryStrong: 'Very Strong',
    },
    assumptions: {
      loading: 'Checking statistical assumptions...',
      loadingDescription: 'Running normality and homogeneity tests. Please wait.',
      badge: 'Note',
      title: 'Statistical Assumption Tests',
      description: 'Use these results to choose an appropriate statistical test.',
      passed: 'Passed',
      failed: 'Not Met',
    },
    normality: {
      title: 'Normality Test (Shapiro-Wilk)',
      normal: 'Normal',
      nonNormal: 'Non-normal',
      statLabel: 'Statistic: ',
      normalInterpretation: '✓ Normality assumption met (p ≥ 0.05). Parametric tests applicable.',
      nonNormalInterpretation: '⚠ Normality assumption violated (p < 0.05). Consider non-parametric tests.',
    },
    homogeneity: {
      title: 'Homogeneity Test (Levene)',
      equal: 'Equal variance',
      unequal: 'Unequal variance',
      statLabel: 'Statistic: ',
      equalInterpretation: '✓ Equal variance assumption met (p ≥ 0.05).',
      unequalInterpretation: '⚠ Equal variance assumption violated (p < 0.05). Consider Welch test.',
    },
    highlight: {
      description: (column: string, count: number) => `${count} outliers highlighted for variable ${column}`,
      clearButton: 'Clear highlights',
      notFound: 'Selected rows not found. The data may have changed.',
    },
    preview: {
      title: 'Data Preview',
      topN: (n: number) => `Top ${n} rows`,
      viewAll: (n: number) => `View All (${n} rows)`,
      fullDataInstruction: (n: number) => `Click "View All Data" above to see all ${n} rows.`,
    },
    warnings: {
      fewNumericVars: 'Fewer than 2 numeric variables. Correlation analysis is limited.',
      correlationRequires: 'Correlation analysis requires at least 2 numeric variables.',
      currentStatus: (numeric: number, categorical: number) => `Current: ${numeric} numeric, ${categorical} categorical`,
      nextStepHint: 'You can select a suitable analysis method in the next step.',
    },
    replaceMode: {
      title: 'Upload a different data file',
      cancel: 'Cancel',
      button: 'Replace Data',
    },
    fallbackFileName: 'Uploaded Data',
  },

  results: {
    effectSizeLabels: {
      small: 'Small',
      medium: 'Medium',
      large: 'Large',
      veryLarge: 'Very Large',
    },
    noResults: 'Please run an analysis first.',
    noResultsDescription: 'Please run a statistical analysis first.',
    conclusion: {
      assumptionWarning: '⚠️ Some assumptions not met — interpret with caution',
      significant: '✓ Statistically significant difference found',
      notSignificant: 'No statistically significant difference found',
    },
    statistics: {
      statistic: 'Test Statistic',
      statisticTooltip: 'Test statistic: measures how extreme the sample data is under the null hypothesis.',
      pValue: 'p-value',
      pValueTooltip: 'If p < 0.05, the result is statistically significant.',
      effectSize: 'Effect Size',
      effectSizeTooltip: 'Effect size: indicates practical significance. Small (<0.2), Medium (0.2–0.5), Large (>0.5)',
      significant: 'Significant',
      notSignificant: 'Not significant',
    },
    ai: {
      loading: 'AI is interpreting the results...',
      detailedLabel: 'Detailed Interpretation',
      reinterpret: 'Re-interpret',
      retry: 'Retry',
      defaultError: 'An error occurred during AI interpretation.',
    },
    sections: {
      detailedResults: 'Detailed Results',
      confidenceInterval: 'Confidence Interval',
      apaFormat: 'APA Format',
      diagnostics: 'Diagnostics & Recommendations',
      caution: 'Caution',
      recommendations: 'Recommendations',
      warnings: 'Warnings',
      alternatives: 'Alternative Methods',
    },
    metadata: {
      file: 'File: ',
      data: 'Data: ',
      variables: 'Variables: ',
      rowsCols: (rows: number, cols: number) => `${rows} rows × ${cols} columns`,
    },
    buttons: {
      saved: 'Saved',
      save: 'Save',
      generating: 'Generating...',
      pdf: 'PDF',
      copied: 'Copied',
      copy: 'Copy',
      saveTemplate: 'Save as Template',
      reanalyze: 'Reanalyze with New Data',
      newAnalysis: 'New Analysis',
      export: 'Export',
      exporting: 'Exporting...',
      exportDocx: 'Word Document (DOCX)',
      exportExcel: 'Excel Spreadsheet',
      exportHtml: 'HTML (.html)',
      exportWithOptions: 'Export with options',
      backToVariables: 'Back to Variables',
    },
    save: {
      defaultName: (date: string) => `Analysis ${date}`,
      promptMessage: 'Enter analysis name:',
      success: 'Saved successfully',
      errorTitle: 'Save failed',
      unknownError: 'Unknown error',
    },
    toast: {
      reanalyzeReady: 'Please upload new data',
      reanalyzeMethod: (name: string) => `${name} analysis is ready`,
      newAnalysis: 'Starting a new analysis',
      pdfSuccess: 'PDF report generated',
      pdfError: 'PDF generation failed',
      exportSuccess: 'Export complete',
      exportError: 'Export failed',
      copyWithAi: 'Results + AI interpretation copied',
      copySuccess: 'Results copied',
      copyError: 'Copy failed',
      templateSaved: 'Template saved',
      chartsNotReady: 'Chart export is currently in preparation. Only tables/text are included in this file.',
    },
    exportDialog: {
      title: 'Export Options',
      description: 'Choose content to include in the export file.',
      formatLabel: 'File Format',
      contentLabel: 'Include Content',
      includeInterpretation: 'Result Interpretation',
      includeRawData: 'Raw Data Preview (max 200 rows)',
      includeMethodology: 'Analysis Methodology',
      includeReferences: 'References',
      includeCharts: 'Charts (coming soon, currently excluded)',
      cancel: 'Cancel',
      confirm: 'Export',
    },
    clipboard: {
      itemHeader: 'Item',
      valueHeader: 'Value',
      statistic: (name: string) => `Statistic (${name})`,
      df: 'Degrees of Freedom (df)',
      effectSize: 'Effect Size',
      confidenceInterval: '95% Confidence Interval',
      interpretation: 'Interpretation:',
      aiInterpretation: 'AI Interpretation',
      aiSeparator: '--- AI Interpretation ---',
    },
  },

  dataUpload: {
    errors: {
      fileTooLarge: (maxMB: number) => `File is too large. Maximum ${maxMB}MB allowed.`,
      fileSizeExceeded: 'File size exceeded',
      currentFileSize: (sizeMB: string) => `Current: ${sizeMB}MB`,
      validationFailed: 'File validation failed',
      noDataInFile: 'No data found in file.',
      noDataTitle: 'No data',
      noValidData: 'No processable data found in file',
      tooManyRows: (maxRows: string) => `Too many rows. Maximum ${maxRows} rows allowed.`,
      dataSizeExceeded: 'Data size exceeded',
      currentRowCount: (rows: string) => `Current: ${rows} rows`,
      processingError: 'An error occurred while processing the file.',
      excelValidationFailed: 'Excel file validation failed',
      excelFileError: 'Excel file error',
      excelProcessingError: 'An error occurred while processing the Excel file.',
      unsupportedFormat: 'Unsupported file format.',
      unsupportedFormatTitle: 'Unsupported file format',
      csvRequired: 'Please upload a CSV file',
      sheetProcessingError: 'An error occurred while processing the Excel sheet.',
    },
    success: {
      fileUploaded: 'File uploaded successfully',
      excelFileUploaded: 'Excel file uploaded successfully',
      sheetLoaded: 'Excel sheet loaded successfully',
      dataLoaded: (rows: string) => `Loaded ${rows} rows of data`,
    },
    buttons: {
      selectFile: 'Select file',
      changeFile: 'Change file',
      uploading: 'Uploading...',
      loading: 'Loading...',
      cancel: 'Cancel',
      loadSelectedSheet: 'Load selected sheet',
      deleteRecentFile: 'Delete recent file',
    },
    labels: {
      dragOrClick: 'Drag & drop or click to upload',
      dropHere: 'Drop file here',
      fileSpecifications: 'Max 100,000 rows | Supported: CSV, Excel',
      recentFiles: 'Recently uploaded files',
      recentFilesNote: '* Recent file list is for reference only. Please re-upload the file.',
      selectSheet: 'Select Excel Sheet',
      sheetsFound: (count: number) => `${count} sheets found. Select a sheet to analyze.`,
      selectSheetPlaceholder: 'Select a sheet',
      sheetInfo: (name: string, rows: string, cols: number) => `${name} (${rows} rows × ${cols} cols)`,
      processing: (current: string, total: string) => `Processing... ${current} / ${total} rows`,
      estimatedTime: (seconds: number) => `Estimated time remaining: ${seconds}s`,
      analyzing: 'Analyzing file...',
      helpText: 'First row must contain variable names (headers). For Excel files with multiple sheets, you can select one.',
      fileMetadata: (rows: string, size: string, time: string) => `${rows} rows · ${size} · ${time}`,
    },
    warnings: {
      highMemoryTitle: 'High memory usage',
      highMemoryDescription: 'Browser memory usage is high. Close other tabs or use a smaller dataset.',
    },
    toast: {
      selectSheet: 'Select sheet',
      sheetsFoundDescription: (count: number) => `${count} sheets found. Select a sheet to analyze.`,
    },
  },

  dataValidation: {
    status: {
      dataRequired: 'Please upload data first.',
      failed: 'Data validation failed',
      warningComplete: 'Data validation complete (with warnings)',
      readyComplete: 'Data ready',
    },
    labels: {
      sampleSize: 'Sample Size',
      analyzableVariables: 'Analyzable Variables',
      numeric: 'Numeric',
      categorical: 'Categorical',
      dataQuality: 'Data Quality',
      uploadedFile: 'Uploaded File',
      missing: 'Missing',
      columnsCount: (count: number) => `${count} columns`,
      otherVariables: (count: number) => `and ${count} more variables...`,
    },
    badges: {
      largeSample: 'Large sample',
      smallSample: 'Small sample',
      numeric: 'Numeric',
      categorical: 'Categorical',
      idSequential: 'ID/Sequential',
    },
    quality: {
      perfect: 'Perfect',
      good: 'Good',
      caution: 'Caution',
    },
    units: {
      count: '',
    },
    sections: {
      needsAttention: 'Needs Attention',
      variableSummary: 'Variable Summary',
    },
    table: {
      variableName: 'Variable',
      type: 'Type',
      uniqueValues: 'Unique',
      missing: 'Missing',
      excluded: 'Excluded',
    },
    idDetection: {
      label: 'ID excluded:',
      heading: 'ID/Sequential detection:',
      explanation: 'These variables appear to be auto-generated identifiers and will be automatically excluded from analysis.',
    },
    recommendations: {
      title: 'Available analyses for this data',
      hint: 'Select an analysis purpose in the next step and AI will recommend the best method.',
      twoGroupComparison: 'Two-group comparison (t-test, Mann-Whitney)',
      multiGroupComparison: 'Multi-group comparison (ANOVA, Kruskal-Wallis)',
      correlation: 'Correlation analysis (Pearson, Spearman)',
      regression: 'Regression analysis (predictive model)',
      chiSquare: 'Chi-square test (categorical association)',
    },
    warnings: {
      canContinue: 'There are warnings but analysis can proceed',
    },
    fallback: {
      noFileName: 'No filename',
    },
  },

  naturalLanguageInput: {
    description: 'Describe what you want to analyze. AI will recommend suitable statistical methods.',
    dataSummary: {
      dimension: (rows: number, cols: number) => `${rows} rows x ${cols} cols`,
      numeric: (count: number) => `${count} numeric`,
      categorical: (count: number) => `${count} categorical`,
      privacyNotice: 'Raw data is not transmitted; only summary statistics are sent to AI.',
    },
    input: {
      placeholder: 'e.g., "I want to compare means between two groups"',
      sendHint: 'Send',
      newlineHint: 'New line',
    },
    examplesLabel: 'Examples:',
    examples: [
      'I want to compare mean differences between two groups',
      'I want to know the correlation between variables',
      'I want to analyze trends over time',
      'I want to compare means across multiple groups',
    ],
    loadingMessages: [
      'Analyzing your data...',
      'Comparing statistical methods...',
      'Finding the best analysis method...',
    ],
    error: {
      title: 'Error occurred',
    },
    aiAnalysis: {
      label: 'AI Analysis',
    },
    recommendation: {
      badgeLabel: 'AI Recommended',
      confidenceUnit: '% confidence',
      reasoningTitle: 'Reasoning',
      variableAssignmentTitle: 'Variable Assignment',
      preprocessingTitle: (count: number) => `Preprocessing suggestions (${count})`,
      alternativesTitle: (count: number) => `Alternatives (${count})`,
      variableRoles: {
        dependent: 'Dependent',
        independent: 'Independent',
        factor: 'Factor',
        covariate: 'Covariate',
        within: 'Within-subject',
        between: 'Between-subject',
      },
    },
    buttons: {
      getRecommendation: 'Get recommendation',
      analyzing: 'Analyzing...',
      goToGuided: 'Go to guided questions',
      selectMethod: 'Use this method',
      retry: 'Ask again',
      select: 'Select',
      guidedQuestions: 'Guided questions',
      browseAll: 'Browse all methods',
    },
    providers: {
      keyword: 'Keyword',
    },
  },

  methodSelector: {
    searchPlaceholder: 'Search methods... (↑↓ navigate, Enter select)',
    methodCount: (count: number) => `${count} methods`,
    searchPrefix: 'Search: ',
    selected: 'Selected: ',
    recommendedBadge: 'Recommended',
    requirementNotMet: 'Requirements not met',
    showBrief: 'Show less',
    showDetails: 'Show details',
    noDataProfile: 'No data profile available',
    fitScoreDetails: 'Fit Score Details',
    sampleSizeRequirement: (rows: number, min: number) => `Sample size: ${rows} (minimum ${min} required)`,
    numericVarsCount: (count: number) => `Numeric variables: ${count}`,
    categoricalVarsCount: (count: number) => `Categorical variables: ${count}`,
    assumptions: {
      normality: 'Normality',
      homogeneity: 'Homogeneity',
      needsTest: 'Needs testing',
      met: 'Met',
      notMet: 'Not met',
    },
    aiRecommended: (count: number) => `AI Recommended (${count})`,
    otherMethods: (count: number) => `Other methods (${count})`,
    noSearchResults: (query: string) => `No methods found for "${query}"`,
    clearSearch: 'Clear search',
  },

  methodBrowser: {
    compatibilityStatus: {
      warning: 'Caution',
      incompatible: 'Incompatible',
    },
    tooltips: {
      warning: 'Caution needed',
      incompatible: 'Not available',
    },
    aiRecommendation: {
      label: 'AI Recommended',
      badge: 'Best Match',
    },
    searchPlaceholder: 'Search methods...',
    selectedLabel: 'Selected',
    selectedPrefix: 'Selected: ',
    methodsLabel: 'methods',
    requirementsNotMet: 'Requirements not met',
    useThisButton: 'Use This',
    noResultsMessage: (query: string) => `No methods found for "${query}"`,
    clearSearchButton: 'Clear search',
  },

  template: {
    saveTitle: 'Save as Template',
    saveDescription: 'Save the current analysis settings as a template to quickly run the same analysis with new data later.',
    manageTitle: 'Manage Templates',
    manageDescription: 'Manage and select saved analysis templates',
    editTitle: 'Edit Template',
    editDescription: 'Edit the template name and description',
    savedTemplates: 'Saved Templates',
    loading: 'Loading...',
    templateCount: (count: number) => `${count}`,
    usageCount: (count: number) => `Used ${count} time${count !== 1 ? 's' : ''}`,
    usageCountShort: (count: number) => `${count}x`,
    methodCategories: {
      'descriptive': 'Descriptive', 't-test': 't-test', 'anova': 'ANOVA',
      'regression': 'Regression', 'correlation': 'Correlation', 'chi-square': 'Chi-square',
      'nonparametric': 'Nonparametric', 'advanced': 'Advanced', 'timeseries': 'Time Series',
      'pca': 'PCA', 'clustering': 'Clustering', 'psychometrics': 'Psychometrics',
      'design': 'Experimental Design', 'survival': 'Survival Analysis',
    },
    variableLabels: { dependent: 'Dependent Variable', independent: 'Independent Variable', group: 'Group Variable', factor: 'Factor' },
    labels: { nameRequired: 'Template Name *', descriptionOptional: 'Description (optional)', name: 'Name', description: 'Description' },
    placeholders: { name: 'e.g., Experiment Data t-test', description: 'Add a note for future reference', search: 'Search templates...' },
    buttons: {
      cancel: 'Cancel', save: 'Save', saving: 'Saving...', edit: 'Edit',
      delete: 'Delete', deleteAll: 'Delete All Templates', deleteAllConfirm: 'Delete All', viewAll: 'View All',
    },
    errors: { nameRequired: 'Please enter a template name.', settingsIncomplete: 'Analysis settings are not complete.', saveFailed: 'An error occurred while saving.' },
    sortOptions: { 'recent': 'Recent', 'usage': 'Most Used', 'name': 'Name', 'created': 'Created' },
    timeAgo: {
      justNow: 'Just now',
      minutesAgo: (n: number) => `${n} min ago`,
      hoursAgo: (n: number) => `${n} hr ago`,
      daysAgo: (n: number) => `${n} day${n !== 1 ? 's' : ''} ago`,
    },
    empty: { title: 'No saved templates', description: 'Click "Save as Template" after completing an analysis' },
    dialogs: {
      deleteTitle: 'Delete Template',
      deleteConfirm: (name: string) => `Are you sure you want to delete "${name}"?`,
      clearTitle: 'Delete All Templates',
      clearConfirm: (count: number) => `Are you sure you want to delete all ${count} template${count !== 1 ? 's' : ''}?`,
      irreversible: 'This action cannot be undone.',
    },
  },

  validationDetails: {
    numericStats: {
      title: 'Numeric Variable Detailed Statistics',
      headers: {
        variableName: 'Variable', mean: 'Mean', median: 'Median', stdDev: 'Std Dev',
        cv: 'CV(%)', skewness: 'Skewness', kurtosis: 'Kurtosis', min: 'Min', max: 'Max', outliers: 'Outliers',
      },
      explanation: {
        cvLabel: 'CV (Coefficient of Variation)', cvDescription: 'Standard deviation divided by mean as a percentage. Stable if below 15%',
        skewnessLabel: 'Skewness', skewnessNormal: '|val| < 0.5 Normal', skewnessModerate: '|val| < 1 Slight skew', skewnessSevere: '|val| >= 1 Severe skew',
        kurtosisLabel: 'Kurtosis', kurtosisNormal: '|val| < 1 Normal', kurtosisModerate: '|val| < 3 Slightly peaked/flat', kurtosisSevere: '|val| >= 3 Very peaked/flat',
      },
      problemGuide: {
        title: 'Data Problem Resolution Guide',
        skewnessTitle: 'Skewness Issues (|skewness| >= 1) Solutions:',
        skewnessPositive: 'Positive skew (right tail): Apply log, sqrt, or Box-Cox transformation',
        skewnessNegative: 'Negative skew (left tail): Apply square, exponential, or reciprocal transformation',
        skewnessAlternative: 'Alternative: Use non-parametric tests (Mann-Whitney U, Kruskal-Wallis)',
        kurtosisTitle: 'Kurtosis Issues (|kurtosis| >= 3) Solutions:',
        kurtosisHigh: 'High kurtosis (peaked): Remove outliers, apply Winsorization or Trimming',
        kurtosisLow: 'Low kurtosis (flat): Check data range, consider multimodal distribution',
        kurtosisAlternative: 'Alternative: Use robust statistical methods or bootstrap',
        outlierTitle: 'Outlier Issues (>10%) Solutions:',
        outlierIdentify: 'Identify cause: Distinguish input errors, measurement errors, true extreme values',
        outlierTreatment: 'Treatment: Remove, Winsorize (replace extremes with boundary values), transform',
        outlierAlternative: 'Alternative: Robust regression, median-based analysis, M-estimators',
        generalTitle: 'General Recommendations:',
        generalCompare: 'Compare results before and after transformation to select optimal method',
        generalNonParametric: 'Consider non-parametric tests first if multiple issues exist',
        generalPreserveOriginal: 'Preserve original data for reference during interpretation',
        generalCLT: 'Central Limit Theorem applicable if sample size is sufficient (n>=30)',
      },
    },
    assumptions: {
      parametricAvailable: 'Parametric Tests Available',
      nonParametricRecommended: 'Non-parametric Tests Recommended',
      violationsFound: 'Assumption Violations Found:',
      recommendedMethods: 'Recommended Analysis Methods:',
      violationKeywords: { normality: 'normality', homogeneity: 'homogeneity', outlier: 'outlier', sampleSize: 'sample', etcSuffix: ' etc.' },
      badges: { correlationAvailable: 'Correlation Available', groupComparisonAvailable: 'Group Comparison Available', regressionAvailable: 'Regression Available' },
      parametricMethods: {
        tTest: { name: 't-test', description: 'Compare means of two groups' },
        anova: { name: 'ANOVA', description: 'Compare means of three or more groups' },
        linearRegression: { name: 'Linear Regression', description: 'Prediction and relationship analysis' },
      },
      nonParametricMethods: {
        mannWhitney: { name: 'Mann-Whitney U', description: 'Alternative to t-test' },
        kruskalWallis: { name: 'Kruskal-Wallis', description: 'Alternative to ANOVA' },
        spearman: { name: 'Spearman Correlation', description: 'Alternative to Pearson' },
        robustRegression: { name: 'Robust Regression', description: 'Resistant to outliers' },
      },
    },
    dataEditGuide: {
      title: 'Data Editing Guide',
      introMessage: 'You may need to transform or edit data to meet statistical assumptions. Refer to the methods below to prepare your data.',
      warningMessage: 'Caution: Always back up original data before transformation. Choose carefully as transformations can affect interpretation.',
      normality: { title: 'Normality Issues', methodsLabel: 'Transformation Methods:', logTransform: 'Log transform: For right-skewed data', sqrtTransform: 'Square root transform: For mild skew', boxCoxTransform: 'Box-Cox transform: Automatic optimal lambda' },
      outlierHandling: { title: 'Outlier Handling', methodsLabel: 'Treatment Methods:', removal: 'Removal:', winsorization: 'Winsorization:', iqrMethod: 'IQR Method:' },
      missingValues: { title: 'Missing Value Handling', methodsLabel: 'Imputation Methods:', meanImputation: 'Mean Imputation:', medianImputation: 'Median Imputation:', deletion: 'Deletion:' },
    },
    outlier: {
      title: 'Outlier Analysis', detectionMethod: 'Detection Method', position: 'Position',
      outlierValues: 'Outlier Values', noOutliers: 'No outliers detected',
      treatmentTitle: 'Treatment Suggestions:',
      treatmentUnder5: 'Under 5%: Proceed as-is, consider robust statistics',
      treatment5to10: '5-10%: Consider Winsorization or Trimming',
      treatmentOver10: 'Over 10%: Identify cause first, remove or transform',
      outlierCount: (count: number, percent: number) => `${count} outliers (${percent.toFixed(1)}%)`,
      lowerCount: (count: number) => `${count} lower`,
      upperCount: (count: number) => `${count} upper`,
      moreValues: (count: number) => ` ... and ${count} more`,
    },
    categorical: {
      title: 'Categorical Variable Frequency Analysis',
      skewedDistribution: 'Skewed Distribution', sparseCategory: 'Sparse Category',
      emptyValue: '(empty)', noFrequencyInfo: 'No frequency information',
      categoryCount: (count: number) => `${count} categories`,
      itemCount: (count: number) => `${count} items`,
      moreCategories: (count: number) => `... and ${count} more categories`,
      missingCount: (count: number) => `Missing: ${count}`,
    },
    additional: {
      title: 'Additional Basic Statistics',
      labels: { quartileRange: 'Quartile Range', iqr: 'IQR', range: 'Range', standardError: 'Std Error (SE)', confidenceInterval: '95% CI' },
    },
  },

  validationSummary: {
    detailAnalysisTitle: (columnName: string) => `${columnName} Detail Analysis`,
    chartTypes: { histogram: 'Histogram', boxplot: 'Box Plot', ariaLabel: 'Chart type selection' },
    histogramHoverTemplate: '%{x}: %{y}<extra></extra>',
    heatmapHoverTemplate: '%{x} vs %{y}: %{z:.2f}<extra></extra>',
    axisLabels: { frequency: 'Frequency' },
    statistics: {
      mean: 'Mean', stdDev: 'Std Dev', minMax: 'Min/Max', outliers: 'Outliers',
      meanLabel: 'Mean', stdDevLabel: 'Std Dev', modeLabel: 'Mode', frequencyLabel: 'Frequency',
    },
    outlierCount: (count: number) => `${count}`,
    categoryFrequencyTitle: 'Category Frequency',
    mixedTypeMessage: 'Visualization is limited for mixed-type variables.',
    correlationTitle: 'Variable Correlations',
    tableHeaders: { variableName: 'Variable', type: 'Type', missingValues: 'Missing', uniqueValues: 'Unique', statistics: 'Statistics', actions: 'Actions' },
    typeLabels: { numeric: 'Numeric', categorical: 'Categorical', mixed: 'Mixed' },
    viewDetailAriaLabel: (name: string) => `View ${name} variable details`,
    buttons: { view: 'View' },
    cardTitle: 'Data Validation Results',
    errorCount: (count: number) => `${count} error(s)`,
    warningCount: (count: number) => `${count} warning(s)`,
    statusNormal: 'Normal',
    summaryLabels: { totalRows: 'Total Rows', totalColumns: 'Total Columns', missingValues: 'Missing Values', duplicateRows: 'Duplicate Rows' },
    sectionLabels: { errors: 'Errors', warnings: 'Warnings' },
    allPassedMessage: 'All data validation checks passed.',
  },

  resultsVisualization: {
    labels: { mean: 'Mean', sampleSize: 'Sample Size', data: 'Data' },
    significantDifference: (pValue: string) => `Statistically significant difference found (p = ${pValue})`,
    groupComparison: { title: 'Group Mean Comparison (Mean +/- Std Dev)' },
    correlation: { title: 'Correlation Analysis', coefficientLabel: 'Correlation Coefficient', determinationLabel: 'Coefficient of Determination' },
    regression: { title: 'Regression Analysis Results', independentVar: 'Independent Variable', dependentVar: 'Dependent Variable', regressionLine: 'Regression Line', equationLabel: 'Regression Equation' },
    nonparametric: { title: 'Nonparametric Test Results (Median/Mean +/- Variance)', medianMean: 'Median/Mean' },
    pca: {
      title: 'Variance Explained', individualVariance: 'Individual Variance', cumulativeVariance: 'Cumulative Variance',
      noDataMessage: 'No variance explained data available.',
      summary: (componentCount: number, totalPercent: string) => `${componentCount} principal components explain ${totalPercent}% of total variance.`,
    },
    cluster: { title: 'Cluster Analysis Results', dimension1: 'Dimension 1', dimension2: 'Dimension 2', clusterCount: 'Number of Clusters' },
    reliability: { title: 'Item-Total Correlation', itemLabel: (index: number) => `Item ${index}`, noDataMessage: 'No item correlation data available.', acceptable: 'Acceptable', low: 'Low' },
    power: { title: 'Power Curve', powerLabel: 'Power', currentPower: 'Current Power', requiredSampleSize: 'Required Sample Size' },
    fallback: {
      title: 'Analysis Result Visualization',
      preparing: (method: string) => `Preparing visualization for this analysis type (${method}).`,
      seeBelow: 'Result data can be found in the section below.',
    },
    methodCategories: {
      test: 'Test',
      correlation: 'Correlation',
      regression: 'Regression',
      nonparametric: 'Nonparametric',
      pca: 'PCA',
      factor: 'Factor Analysis',
      cluster: 'Cluster Analysis',
      kMeans: 'K-Means Clustering',
      reliability: 'Reliability',
      power: 'Power Analysis',
    },
  },

  methodSpecificResults: {
    regression: {
      sectionTitle: 'Model Fit',
      rSquaredTooltip: 'Coefficient of determination: percentage of variance in the dependent variable explained by independent variables',
      adjRSquaredTooltip: 'Adjusted R\u00B2: R\u00B2 corrected for the number of predictors',
      rmseTooltip: 'Root Mean Square Error: prediction accuracy (lower is better)',
      aicTooltip: 'Akaike Information Criterion: model selection metric (lower is better)',
      bicTooltip: 'Bayesian Information Criterion: model selection metric (lower is better)',
      interceptLabel: 'Intercept', interceptTooltip: 'Regression intercept (y-intercept)',
      vifWarningTitle: 'Multicollinearity Warning',
      vifWarningMessage: (count: number) => `${count} variable(s) have VIF > 5. High correlation among predictors may affect coefficient interpretation.`,
    },
    classification: {
      sectionTitle: 'Classification Performance',
      accuracyLabel: 'Accuracy', accuracyTooltip: 'Proportion of correct predictions among all predictions',
      precisionLabel: 'Precision', precisionTooltip: 'Proportion of true positives among predicted positives',
      recallLabel: 'Recall', recallTooltip: 'Proportion of true positives identified among actual positives',
      f1Tooltip: 'Harmonic mean of precision and recall',
      rocAucTooltip: 'Area under the ROC curve (closer to 1 is better)',
      confusionMatrixLabel: 'Confusion Matrix',
      predicted: (index: number) => `Predicted ${index}`,
      actual: (index: number) => `Actual ${index}`,
    },
    pca: {
      sectionTitle: 'Principal Component / Factor Analysis',
      varianceExplainedLabel: 'Variance Explained', cumulativePrefix: 'Cumulative',
      eigenvalueLabel: (index: number) => `Eigenvalue ${index}`,
      eigenvalueTooltip: (index: number, meetsKaiser: boolean) => `Eigenvalue of component/factor ${index}${meetsKaiser ? ' (meets Kaiser criterion)' : ''}`,
    },
    cluster: {
      sectionTitle: 'Cluster Analysis',
      silhouetteTooltip: 'Cluster quality metric (-1 to 1, higher = better separation). 0.5+ good, 0.7+ excellent',
      dataCountLabel: 'Data Points', dataCountTooltip: 'Number of data points assigned to clusters',
      clusterCountLabel: 'Clusters', clusterCountTooltip: 'Final number of clusters determined',
    },
    descriptive: {
      sectionTitle: 'Descriptive Statistics',
      meanLabel: 'Mean', meanTooltip: 'Arithmetic mean',
      medianLabel: 'Median', medianTooltip: 'Middle value when data is sorted by size',
      stdDevLabel: 'Std Dev', stdDevTooltip: 'Standard measure of data dispersion',
      skewnessLabel: 'Skewness', skewnessTooltip: 'Degree of distribution asymmetry (0 = symmetric)',
      kurtosisLabel: 'Kurtosis', kurtosisTooltip: 'Degree of distribution peakedness (normal = 3)',
      sampleSizeLabel: 'Sample Size', sampleSizeTooltip: 'Number of data points used in the analysis',
    },
    reliability: {
      sectionTitle: 'Reliability Analysis',
      alphaTooltip: 'Internal consistency reliability. 0.7+ acceptable, 0.8+ good, 0.9+ excellent',
      itemCountLabel: 'Item Count', itemCountTooltip: 'Number of items included in reliability analysis',
    },
    power: {
      sectionTitle: 'Statistical Power',
      powerLabel: 'Power', powerTooltip: 'Probability of detecting a real effect. 0.8+ recommended',
      requiredSampleLabel: 'Required Sample', requiredSampleTooltip: 'Minimum sample size needed to achieve target power',
      analysisSampleLabel: 'Analysis Sample', analysisSampleTooltip: 'Sample size used in the power analysis',
    },
  },

  recommendedMethods: {
    smartRecommend: 'Smart Recommendations',
    hide: 'Hide', show: 'Show',
    methodCount: (count: number) => `${count}`,
    aiRecommendTitle: 'Data-driven AI Recommendations',
    recommendedBadge: 'Recommended',
    showBrief: 'Show less', showDetails: 'Show details',
    noDataProfile: 'No data profile information available',
    fitScoreDetails: 'Fit Score Details',
    sampleSize: (rows: number, minRequired: number) => `Sample size: ${rows} (minimum ${minRequired} required)`,
    numericVars: (count: number) => `Numeric variables: ${count}`,
    categoricalVars: (count: number) => `Categorical variables: ${count}`,
    assumptionLabels: { normality: 'Normality', homogeneity: 'Homogeneity' },
    assumptionStatus: {
      needsCheck: 'Needs testing', met: 'Met',
      normalityFailed: 'Not met \u2192 Non-parametric test recommended',
      homogeneityFailed: 'Not met \u2192 Welch test recommended',
    },
  },

  conversationalQuestion: {
    aiAnalyzed: 'AI has analyzed the data',
    aiRecommendNeedsCheck: 'AI Recommendation (needs review)',
    aiReferenceInfo: 'AI Reference Info',
    recommendedBadge: 'Recommended',
    keyboardHint: (optionCount: number) => `Press 1-${optionCount} to select or click an option`,
  },

  variableMapping: {
    title: '\uD83C\uDFAF Auto Variable Mapping',
    editButton: 'Edit Mapping',
    hideButton: 'Hide',
    roles: { dependent: 'Dependent', independent: 'Independent', group: 'Group', time: 'Time', variableList: 'Variables' },
    autoMappingHint: '\uD83D\uDCA1 Auto mapping provides defaults. Click "Edit Mapping" to confirm dependent/independent/group variables.',
  },

  questionFlowNav: {
    backToPurpose: 'Back to Purpose',
    previous: 'Previous',
    restart: 'Start over',
    keyboardHint: 'Enter to proceed \u00B7 Esc to cancel',
    viewResults: 'View Results',
    next: 'Next',
  },

  reanalysis: {
    title: 'Reanalysis Mode',
    description: 'Apply previous analysis settings to new data',
    savedVariableSettings: 'Saved Variable Settings',
    variableRoles: {
      dependentVar: 'Dependent Variable', independentVar: 'Independent Variable', groupVar: 'Group Variable',
      timeVar: 'Time Variable', variables: 'Analysis Variables', covariate: 'Covariate',
      within: 'Within-Subject Factor', between: 'Between-Subject Factor', blocking: 'Blocking Variable',
      event: 'Event Variable', censoring: 'Censoring Variable', weight: 'Weight Variable',
    },
    allVariablesMatch: 'All variables match',
    matchedCount: (n: number) => `${n} variables verified.`,
    typeMismatchWarning: (n: number) => `Type caution: ${n}`,
    readyToAnalyze: 'Ready to analyze.',
    typeCaution: 'Type caution:',
    analyzing: 'Analyzing...',
    runAnalysis: 'Run Analysis',
    variablesMismatch: 'Variables do not match',
    missingVariables: (required: number, missing: number) => `${missing} of ${required} required variables are missing.`,
    pleaseReselectVariables: 'Please reselect variables.',
    editVariables: 'Reselect Variables',
    fixMappingFirst: 'Please fix variable mapping first',
  },

  methodManager: {
    title: 'Statistical Method Manager',
    startAnalysis: (categoryTitle: string) => `Start ${categoryTitle} analysis`,
    notReady: '(Coming soon)',
  },

  chartLabels: {
    theoreticalNormal: 'Theoretical Normal',
    theoreticalQuantile: 'Theoretical Quantile',
    observedValue: 'Observed Value',
    distributionTitle: (colName: string) => `Distribution: ${colName}`,
    value: 'Value',
    frequency: 'Frequency',
    errorMessage: 'Statistical test error',
  },

  flowStateMachine: {
    evidencePrefix: (index: number) => `Evidence ${index + 1}`,
    directSelection: 'Direct Selection',
    directSelectionDescription: 'User directly selected the analysis method',
  },

  decisionTree: {
    steps: {
      normality: 'Normality',
      homogeneity: 'Homogeneity of Variance',
      groupCount: 'Number of Groups',
      sampleType: 'Sample Type',
      variableType: 'Variable Type',
      comparisonTarget: 'Comparison Target',
      analysisType: 'Analysis Type',
      variableCount: 'Number of Variables',
      predictorCount: 'Number of Predictors',
      outcomeVariable: 'Outcome Variable',
      modelType: 'Model Type',
      variableSelection: 'Variable Selection',
      designType: 'Design Type',
      dependentVariable: 'Dependent Variable',
      covariate: 'Covariate',
      analysisPurpose: 'Analysis Purpose',
      seasonality: 'Seasonality',
      defaultStep: 'Default',
    },
    descriptions: {
      singleSample: 'Single sample',
      twoGroupComparison: '2-group comparison',
      threeOrMoreGroupComparison: '3+ group comparison',
      pairedSample: 'Paired sample (same subjects pre/post)',
      independentSample: 'Independent sample (different subjects)',
      sampleVsPopulation: 'Sample vs Population',
      binaryProportionTest: 'Binary proportion test',
      oneSampleTTest: 'One-sample t-test',
      studentTTest: 'Student t-test',
      repeatedMeasurement: 'Repeated measurement (same subjects at multiple time points)',
      binaryCochranQ: 'Binary categorical repeated measures → Cochran Q test',
      binaryMcNemar: 'Binary categorical → McNemar test',
      independentGroup: 'Independent groups',
      mixedDesignMixedModel: 'Mixed design → Mixed-effects model',
      multivariateMANOVA: 'Multivariate → MANOVA',
      covariateANCOVA: 'Covariate control → ANCOVA',
      oneWayANOVA: 'One-way ANOVA',
      medianComparisonMood: 'Median comparison → Mood test',
      correlationAnalysis: 'Correlation analysis',
      allNumeric: 'All numeric',
      twoVariables: '2 variables',
      threeOrMoreVariables: '3+ variables',
      categoricalIncluded: 'Categorical variables included',
      predictionRegression: 'Prediction/Regression analysis',
      simpleRegression: 'Simple regression',
      multipleRegression: 'Multiple regression',
      categoricalLogistic: 'Categorical included → Logistic regression',
      dataExploration: 'Data exploration',
      meanVisualization: 'Mean visualization',
      binaryProbabilityTest: 'Binary probability test',
      randomnessTest: 'Randomness test',
      twoDistributionComparison: 'Two distribution comparison',
      descriptiveStats: 'Descriptive statistics',
      numericMeanStd: 'Numeric → Mean, standard deviation, etc.',
      categoricalFreqRatio: 'Categorical → Frequency, proportion',
      normalityTest: 'Normality test',
      frequencyAnalysis: 'Frequency analysis',
      doseResponseAnalysis: 'Dose-response analysis',
      optimizationExperiment: 'Optimization experiment',
      autoVariableStepwise: 'Automatic variable selection → Stepwise regression',
      simpleModel: 'Simple model',
      multipleModel: 'Multiple model',
      continuousLinearRegression: 'Continuous → Linear regression',
      binaryLogisticRegression: 'Binary → Logistic regression',
      countPoissonRegression: 'Count → Poisson regression',
      multiclassMultinomialLogistic: 'Multiclass → Multinomial logistic',
      ordinalOrdinalLogistic: 'Ordinal → Ordinal logistic',
      futureForecast: 'Future forecast',
      seasonalSARIMA: 'Seasonal pattern → SARIMA',
      noSeasonalARIMA: 'No seasonality → ARIMA',
      patternDecomposition: 'Pattern decomposition',
      stationarityTest: 'Stationarity test',
      trendTest: 'Trend test',
      timeseriesAnalysis: 'Time series analysis',
      survivalCurveEstimation: 'Survival curve estimation',
      groupSurvivalComparison: 'Group survival comparison',
      hazardFactorAnalysis: 'Hazard factor analysis',
      covariateYesCox: 'Covariate present → Cox regression',
      covariateNone: 'No covariate',
      dimensionReduction: 'Dimension reduction',
      latentFactorExtraction: 'Latent factor extraction',
      similarGrouping: 'Similar grouping',
      groupClassification: 'Group classification/prediction',
      multivariateAnalysis: 'Multivariate analysis',
      sampleSizeCalculation: 'Sample size calculation',
      powerCalculation: 'Power calculation',
      reliabilityMeasurement: 'Measurement reliability',
      utilityAnalysis: 'Research design tools',
      defaultDescriptive: 'Default descriptive statistics analysis',
      proportionComparison: 'Proportion comparison',
      normalMetParametric: 'Normal distribution met → Parametric test',
      normalNotMetNonparametric: 'Normal distribution not met → Non-parametric test',
      normalMetPrefix: 'Normal distribution met → ',
      normalNotMetPrefix: 'Normal distribution not met → ',
      homoMet: 'Equal variance met',
      homoMetPrefix: 'Equal variance met → ',
      homoNotMetWelch: 'Equal variance not met → Welch\'s test',
      homoUncheckedWelch: 'Equal variance unchecked → Welch\'s test (safe)',
    },
    reasons: {
      exactTestNeeded: 'When an exact test is needed',
      signRankWhenNotNormal: 'Signed-rank test when normality is not met',
      cltRobustN30: 'Robust by Central Limit Theorem when n >= 30',
      cltRobustNPerGroup30: 'Robust by Central Limit Theorem when n/group >= 30',
      crosstabForm: 'When data is in cross-tabulation form',
      ordinalData: 'For ordinal data',
      safeAlternativeUncertain: 'Safe alternative when normality is uncertain',
      ordinalOrDirectional: 'When only ordinal or directional information matters',
      noEqualVarianceNeeded: 'Usable without equal variance assumption',
      nonparametricAlternative: 'Non-parametric alternative',
      equalVarianceConfirmed: 'Usable when equal variance is confirmed',
      robustN30: 'Robust when n >= 30',
      twoTimepoints: 'When comparing only 2 time points',
      sphericityViolated: 'When sphericity assumption is violated',
      simpleRepeatedMeasure: 'For simple repeated measures',
      individualDVAnalysis: 'When analyzing dependent variables individually',
      covariateNotNeeded: 'When covariate control is not needed',
      fullDistributionComparison: 'When comparing full distributions',
      medianComparisonPurpose: 'When the purpose is median comparison',
      simpleCorrelation: 'Simple correlation matrix',
      spearmanForOrdinal: 'Use Spearman for ordinal variables',
      descriptiveOnly: 'When only descriptive statistics are needed',
      descriptiveTableAlternative: 'Alternative using descriptive statistics table',
      largeApproximation: 'When using large sample approximation',
      medianDifference: 'When median difference is of interest',
      detailedExploration: 'For detailed exploration',
      comparisonDistribution: 'When comparing distributions',
      expectedFrequency: 'When comparing with expected frequencies',
      binaryRateTest: 'For binary rate testing',
      explorationWithViz: 'For exploration with visualization',
      linearRelationship: 'For linear trend testing',
      simplePrediction: 'For simple prediction',
      allVariablesIncluded: 'When including all variables',
      variableSelectionNeeded: 'When variable selection is needed',
      discriminantAlternative: 'Discriminant analysis alternative',
      ordinalCategory: 'For ordinal categories',
      ignoreOrder: 'When ignoring order',
      seasonalPatternAnalysis: 'When analyzing seasonal patterns before forecasting',
      logRankForGroupComparison: 'Log-rank test for group comparison',
      covariateControlNeeded: 'When covariate control is needed',
      addCovariate: 'When adding covariates',
      latentFactorInterpretation: 'When latent factor interpretation is needed',
      dimensionReductionOnly: 'When only dimension reduction is needed',
      groupAlreadyDefined: 'When groups are already defined',
      binaryClassification: 'For binary classification',
      groupNotDefined: 'When groups are not defined',
    },
    warnings: {
      sphericity: 'Check Mauchly sphericity test. Apply Greenhouse-Geisser correction if violated.',
      randomEffects: 'Random effects structure must be chosen carefully.',
      multivariateNormality: 'Multivariate normality and Box M test should be verified.',
      regressionHomogeneity: 'Homogeneity of regression slopes assumption should be verified.',
      spearmanOutliers: 'Select Spearman option when normality is not met or outliers exist.',
      doseResponseRange: 'Sufficient concentration range is needed for EC50/IC50 calculation.',
      experimentalDesign: 'Experimental design (CCD, BBD, etc.) must be appropriate.',
      overfittingCrossValidation: 'Beware of overfitting; cross-validation is recommended.',
      multicollinearity: 'Check multicollinearity (VIF) and residual normality.',
      rocAucHosmerLemeshow: 'Verify goodness of fit with ROC-AUC and Hosmer-Lemeshow test.',
      overdispersion: 'Check for overdispersion; consider negative binomial regression if present.',
      arimaSeasonalOption: 'Select the seasonality option (SARIMA) on the ARIMA page.',
      kpssAdditional: 'Running the KPSS test alongside improves reliability.',
      autocorrelationModifiedMK: 'Use Modified Mann-Kendall if autocorrelation is present.',
      proportionalHazards: 'Proportional hazards assumption must be verified (Schoenfeld residuals).',
      sampleSizePrereqs: 'Study design, effect size, and significance level must be determined in advance.',
      minItemsRequired: 'At least 3 items are required.',
    },
  },

  guidedQuestionData: {
    compare: [
      {
        id: 'comparison_target',
        required: true,
        question: 'What do you want to compare?',
        options: [
          { value: 'mean', label: 'Compare Means', hint: 'Test mean differences between groups' },
          { value: 'proportion', label: 'Compare Proportions', hint: 'Test proportion/percentage differences' },
          { value: 'median', label: 'Compare Medians', hint: 'Test median differences' },
          { value: 'population', label: 'Against Population', hint: 'Sample vs known population value' },
        ],
      },
      {
        id: 'group_count',
        required: true,
        question: 'How many groups are you comparing?',
        options: [
          { value: '1', label: '1 group (vs population)', hint: 'e.g., Sample mean vs reference value' },
          { value: '2', label: '2 groups', hint: 'e.g., Treatment vs Control' },
          { value: '3+', label: '3 or more', hint: 'e.g., Comparing farms A, B, C' },
        ],
      },
      {
        id: 'sample_type',
        required: true,
        question: 'What type of samples do you have?',
        options: [
          { value: 'independent', label: 'Independent samples', hint: 'Different subjects measured' },
          { value: 'paired', label: 'Paired samples', hint: 'Same subjects measured before/after or repeated measures' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: 'What type is your dependent variable?',
        options: [
          { value: 'continuous', label: 'Continuous (numeric)', hint: 'Weight, length, concentration, etc.' },
          { value: 'binary', label: 'Binary (yes/no)', hint: 'Alive/dead, success/failure' },
          { value: 'ordinal', label: 'Ordinal', hint: 'High/medium/low, grades' },
        ],
        autoAnswer: true,
      },
      {
        id: 'normality',
        required: false,
        question: 'Does your data follow a normal distribution?',
        options: [
          { value: 'yes', label: 'Yes (or n >= 30)', hint: 'Parametric tests available' },
          { value: 'no', label: 'No', hint: 'Non-parametric tests recommended' },
          { value: 'check', label: 'Need to check', hint: 'AI will examine data' },
        ],
        autoAnswer: true,
      },
      {
        id: 'homogeneity',
        required: false,
        question: 'Are group variances equal?',
        options: [
          { value: 'yes', label: 'Yes (equal variance)', hint: 'Student t-test / standard ANOVA' },
          { value: 'no', label: 'No (unequal variance)', hint: 'Welch t-test / Welch ANOVA recommended' },
          { value: 'check', label: 'Need to check', hint: 'AI will check Levene test results' },
        ],
        autoAnswer: true,
      },
      {
        id: 'has_covariate',
        required: false,
        question: 'Do you have covariates to control for?',
        options: [
          { value: 'no', label: 'None', hint: 'Standard ANOVA' },
          { value: 'yes', label: 'Yes', hint: 'Consider ANCOVA' },
        ],
      },
      {
        id: 'outcome_count',
        required: false,
        question: 'How many dependent variables?',
        options: [
          { value: '1', label: '1', hint: 'Standard ANOVA' },
          { value: '2+', label: '2 or more', hint: 'Consider MANOVA' },
        ],
      },
      {
        id: 'design_type',
        required: false,
        question: 'What is the experimental design?',
        options: [
          { value: 'simple', label: 'Simple design', hint: 'One independent variable' },
          { value: 'factorial', label: 'Factorial design', hint: 'Multiple independent variables (two-way/three-way ANOVA)' },
          { value: 'mixed', label: 'Mixed design', hint: 'Fixed effects + random effects' },
        ],
      },
    ],
    relationship: [
      {
        id: 'relationship_type',
        required: true,
        question: 'What kind of relationship are you looking for?',
        options: [
          { value: 'correlation', label: 'Correlation', hint: 'Do two variables change together?' },
          { value: 'prediction', label: 'Prediction/Causation', hint: 'Predict Y from X' },
        ],
      },
      {
        id: 'variable_count',
        required: true,
        question: 'How many variables are you analyzing?',
        options: [
          { value: '2', label: '2', hint: 'Simple correlation/regression' },
          { value: '3+', label: '3 or more', hint: 'Multiple regression/partial correlation' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: 'What type are your variables?',
        options: [
          { value: 'numeric', label: 'All numeric', hint: 'Pearson/Regression' },
          { value: 'mixed', label: 'Includes categorical', hint: 'Logistic/Chi-square' },
        ],
        autoAnswer: true,
      },
    ],
    distribution: [
      {
        id: 'analysis_type',
        required: true,
        question: 'What kind of analysis do you want?',
        options: [
          { value: 'describe', label: 'Descriptive statistics', hint: 'Mean, standard deviation, quartiles' },
          { value: 'normality', label: 'Normality test', hint: 'Check data distribution' },
          { value: 'frequency', label: 'Frequency analysis', hint: 'Frequencies/proportions by category' },
          { value: 'explore', label: 'Data exploration', hint: 'Explore with visualizations' },
          { value: 'test_probability', label: 'Binomial probability test', hint: 'Test success probability' },
        ],
      },
      {
        id: 'distribution_goal',
        required: false,
        question: 'What is the specific analysis goal?',
        options: [
          { value: 'explore', label: 'Data exploration', hint: 'Check distributions' },
          { value: 'visualize_means', label: 'Mean visualization', hint: 'Group mean comparison graphs' },
          { value: 'test_probability', label: 'Probability test', hint: 'Binomial test' },
          { value: 'randomness', label: 'Randomness test', hint: 'Runs test' },
          { value: 'distribution_compare', label: 'Distribution comparison', hint: 'Are two distributions the same?' },
        ],
      },
      {
        id: 'variable_type',
        required: true,
        question: 'What type are the variables to analyze?',
        options: [
          { value: 'numeric', label: 'Numeric', hint: 'Continuous data' },
          { value: 'categorical', label: 'Categorical', hint: 'Groups/categories' },
        ],
        autoAnswer: true,
      },
    ],
    prediction: [
      {
        id: 'outcome_type',
        required: true,
        question: 'What type is the outcome you want to predict?',
        options: [
          { value: 'continuous', label: 'Continuous (numeric)', hint: 'Linear regression' },
          { value: 'binary', label: 'Binary (yes/no)', hint: 'Logistic regression' },
          { value: 'count', label: 'Count/Frequency', hint: 'Poisson regression' },
          { value: 'multiclass', label: 'Multiclass', hint: 'Multinomial logistic' },
          { value: 'ordinal', label: 'Ordinal category', hint: 'Ordinal logistic' },
        ],
        autoAnswer: true,
      },
      {
        id: 'predictor_count',
        required: true,
        question: 'How many predictor variables?',
        options: [
          { value: '1', label: '1', hint: 'Simple regression' },
          { value: '2+', label: '2 or more', hint: 'Multiple regression' },
        ],
        autoAnswer: true,
      },
      {
        id: 'variable_selection',
        required: false,
        question: 'How do you want to select variables?',
        options: [
          { value: 'manual', label: 'Manual selection', hint: 'Include all variables' },
          { value: 'automatic', label: 'Automatic selection', hint: 'Stepwise regression' },
        ],
      },
      {
        id: 'modelType',
        required: false,
        question: 'Do you need a special model type?',
        options: [
          { value: 'standard', label: 'Standard regression', hint: 'Standard linear/logistic' },
          { value: 'dose_response', label: 'Dose-response', hint: 'EC50/IC50 curve' },
          { value: 'optimization', label: 'Optimization experiment', hint: 'Response surface analysis' },
        ],
      },
    ],
    timeseries: [
      {
        id: 'goal',
        question: 'What is the purpose of the time series analysis?',
        options: [
          { value: 'forecast', label: 'Future forecast', hint: 'ARIMA, exponential smoothing' },
          { value: 'decompose', label: 'Pattern decomposition', hint: 'Separate trend and seasonality' },
          { value: 'stationarity', label: 'Stationarity test', hint: 'ADF, KPSS tests' },
          { value: 'trend_test', label: 'Trend test', hint: 'Mann-Kendall test' },
        ],
      },
      {
        id: 'seasonality',
        question: 'Is there seasonality (periodic pattern)?',
        options: [
          { value: 'yes', label: 'Yes', hint: 'Seasonal ARIMA (SARIMA)' },
          { value: 'no', label: 'No', hint: 'Standard ARIMA' },
          { value: 'unknown', label: 'Unknown', hint: 'AI will analyze' },
        ],
        autoAnswer: true,
      },
    ],
    survival: [
      {
        id: 'goal',
        question: 'What is the purpose of the survival analysis?',
        options: [
          { value: 'curve', label: 'Survival curve estimation', hint: 'Kaplan-Meier' },
          { value: 'hazard', label: 'Hazard factor analysis', hint: 'Cox proportional hazards regression' },
          { value: 'compare', label: 'Group survival comparison', hint: 'Log-rank test' },
        ],
      },
      {
        id: 'covariate_count',
        question: 'Do you have covariates (risk factors)?',
        options: [
          { value: '0', label: 'None', hint: 'Kaplan-Meier only' },
          { value: '1+', label: '1 or more', hint: 'Consider Cox regression' },
        ],
        autoAnswer: true,
      },
    ],
    multivariate: [
      {
        id: 'goal',
        question: 'What is the purpose of the multivariate analysis?',
        options: [
          { value: 'dimension_reduction', label: 'Dimension reduction', hint: 'PCA - reduce number of variables' },
          { value: 'latent_factors', label: 'Latent factor extraction', hint: 'Factor analysis - discover hidden structure' },
          { value: 'grouping', label: 'Similar grouping', hint: 'Cluster analysis - automatic classification' },
          { value: 'classification', label: 'Group classification/prediction', hint: 'Discriminant analysis - predict groups' },
        ],
      },
    ],
    utility: [
      {
        id: 'goal',
        question: 'What do you want to calculate?',
        options: [
          { value: 'sample_size', label: 'Required sample size', hint: 'Pre-experiment sample size calculation' },
          { value: 'power', label: 'Statistical power', hint: 'Ability to detect effects with current sample' },
          { value: 'reliability', label: 'Measurement reliability', hint: 'Cronbach \u03B1, etc.' },
        ],
      },
    ],
  },

  progressiveCategoryData: [
    {
      id: 'compare',
      title: 'Comparison Analysis',
      description: 'Test differences between groups or compare before/after changes',
      icon: 'GitCompare',
      subcategories: [
        {
          id: 'group-mean',
          title: 'Compare Group Means',
          description: 'Test mean differences across two or more groups',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'mean',
          },
        },
        {
          id: 'pre-post',
          title: 'Before/After Comparison',
          description: 'Analyze changes over time within the same subjects',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'mean',
            sample_type: 'paired',
            group_count: '2',
          },
        },
        {
          id: 'proportion',
          title: 'Compare Proportions',
          description: 'Test differences in proportions or frequencies between groups',
          mapsToPurpose: 'compare',
          presetAnswers: {
            comparison_target: 'proportion',
            variable_type: 'binary',
          },
        },
        {
          id: 'distribution',
          title: 'Distribution & Frequency Analysis',
          description: 'Analyze data distribution shapes or categorical frequencies',
          mapsToPurpose: 'distribution',
        },
      ],
    },
    {
      id: 'relationship',
      title: 'Relationship Analysis',
      description: 'Analyze correlations and associations between variables',
      icon: 'TrendingUp',
      subcategories: [
        {
          id: 'correlation',
          title: 'Correlation Analysis',
          description: 'Analyze relationships between two or more numeric variables',
          mapsToPurpose: 'relationship',
          presetAnswers: {
            relationship_type: 'correlation',
          },
        },
        {
          id: 'categorical-association',
          title: 'Categorical Association Analysis',
          description: 'Analyze associations between categorical variables (chi-square, etc.)',
          mapsToPurpose: 'relationship',
          presetAnswers: {
            variable_type: 'categorical',
          },
        },
      ],
    },
    {
      id: 'prediction',
      title: 'Predictive Analysis',
      description: 'Build models to predict dependent variables from independent variables',
      icon: 'LineChart',
      subcategories: [
        {
          id: 'regression',
          title: 'Numeric Prediction (Regression)',
          description: 'Predict continuous dependent variables',
          mapsToPurpose: 'prediction',
          presetAnswers: {
            outcome_type: 'continuous',
          },
        },
        {
          id: 'classification',
          title: 'Classification Prediction',
          description: 'Predict categorical dependent variables (logistic regression, etc.)',
          mapsToPurpose: 'prediction',
          presetAnswers: {
            outcome_type: 'binary',
          },
        },
      ],
    },
    {
      id: 'advanced',
      title: 'Advanced Analysis',
      description: 'Perform specialized analyses including time series, survival analysis, and multivariate analysis',
      icon: 'Layers',
      subcategories: [
        {
          id: 'timeseries',
          title: 'Time Series Analysis',
          description: 'Analyze temporal data patterns and forecast future values',
          mapsToPurpose: 'timeseries',
        },
        {
          id: 'survival',
          title: 'Survival Analysis',
          description: 'Analyze time-to-event data',
          mapsToPurpose: 'survival',
        },
        {
          id: 'multivariate',
          title: 'Multivariate Analysis',
          description: 'Perform PCA, factor analysis, cluster analysis, etc.',
          mapsToPurpose: 'multivariate',
        },
        {
          id: 'utility',
          title: 'Research Design Tools',
          description: 'Sample size calculation, power analysis, reliability analysis, etc.',
          mapsToPurpose: 'utility',
        },
      ],
    },
  ],

  autoAnswerEvidence: {
    normality: {
      cltGroupSize: (size: number) => `Estimated min group size \u2248 ${size} \u2265 30 (CLT applicable, confirmation recommended)`,
      cltSampleSize: (n: number) => `n=${n} \u2265 30 (Normality can be assumed by Central Limit Theorem)`,
      noTestResult: 'No normality test results available',
      shapiroNormal: (pValueStr: string) => `Shapiro-Wilk p=${pValueStr} > 0.05 (Normal distribution met)`,
      shapiroNotNormal: (pValueStr: string) => `Shapiro-Wilk p=${pValueStr} \u2264 0.05 (Normal distribution not met)`,
      allGroupsNormal: 'All groups follow a normal distribution',
      someGroupsNotNormal: 'Some groups do not follow a normal distribution',
      cannotDetermine: 'Unable to determine normality',
    },
    variableType: {
      noInfo: 'No variable information available',
      allNumeric: (count: number) => `All analysis variables are numeric (${count})`,
      includesCategorical: 'Categorical variables are included',
      pleaseCheck: 'Please check the variable type',
    },
    outcomeType: {
      noDependentSelected: 'No dependent variable has been selected',
      dependentNotFound: 'Dependent variable information not found',
      binaryVariable: (name: string) => `${name} is a binary variable with 2 categories`,
      multiclassVariable: (name: string, count: number) => `${name} has ${count} categories`,
      possibleCountData: (name: string) => `${name} may be count/frequency data`,
      continuousVariable: (name: string) => `${name} is a continuous numeric variable`,
      pleaseCheckOutcome: 'Please check the outcome variable type',
    },
    predictorCount: {
      noIndependentSelected: 'No independent variables have been selected',
      onePredictor: '1 predictor variable selected',
      multiplePredictors: (count: number) => `${count} predictor variables selected`,
    },
    covariateCount: {
      noCovariateSelected: 'No covariates have been selected',
      covariatesSelected: (count: number) => `${count} covariate(s) selected`,
    },
    homogeneity: {
      noTestResult: 'No homogeneity of variance test results available',
      leveneNoP: 'Levene test result available (no p-value information)',
      leveneEqual: (pValueStr: string) => `Levene p=${pValueStr} > 0.05 (Equal variance met)`,
      leveneNotEqual: (pValueStr: string) => `Levene p=${pValueStr} \u2264 0.05 (Equal variance not met \u2192 Welch recommended)`,
      bartlettNoP: 'Bartlett test result available (no p-value information)',
      bartlettEqual: (pValueStr: string) => `Bartlett p=${pValueStr} > 0.05 (Equal variance met)`,
      bartlettNotEqual: (pValueStr: string) => `Bartlett p=${pValueStr} \u2264 0.05 (Equal variance not met \u2192 Welch recommended)`,
      cannotDetermine: 'Unable to determine homogeneity of variance',
    },
    seasonality: {
      needsAnalysis: 'Seasonality can only be determined by analyzing the data',
    },
  },
}
