import type { BlastMarker } from '@biohub/types'

export interface ExampleSequence {
  id: string
  species: string
  marker: BlastMarker
  description: string
  sequence: string
}

export const EXAMPLE_SEQUENCES: ExampleSequence[] = [
  {
    id: 'gadus-morhua',
    species: 'Gadus morhua (대구)',
    marker: 'COI',
    description: '동물 바코딩 표준 — 높은 신뢰도 결과 예상',
    sequence: `>Example_Gadus_morhua_COI
CCTCTACCTGGTGTTTGGTGCCTGAGCCGGAATAGTCGGCACAGCTCTAAG
CCTTCTAATTCGAGCTGAGCTGAGCCAACCAGGCGCCCTTCTAGGCGATGA
CCAAATTTATAATGTAATTGTTACAGCACATGCCTTTGTAATAATTTTCTTT
ATAGTAATACCAATTATAATTGGAGGATTTGGAAACTGACTAGTGCCCCTAA
TGATCGGTGCCCCAGACATAGCATTCCCACGAATAAACAACATAAGTTTCTG
ACTTCTCCCTCCATCATTCCTTCTTCTCCTAGCCTCTTCTGGCGTAGAAGCC
GGAGCAGGAACAGGATGAACTGTATATCCCCCCCTATCAGGCAACCTAGCCC
ATGCCGGAGCATCAGTTGATCTAACAATTTTCTCACTCCACCTGGCAGGTGT
CTCATCAATCCTAGGCGCAATCAACTTTATTACAACAATCATTAACATGAAA
CCCCCAGCCATTTCTCAATACCAAACACCCCTGTTCGTGTGAGCAGTTCTCA
TTACAGCCGTACTACTCCTCCTATCTCTTCCAGTCCTCGCCGCCGGCATTAC
CATGCTTTTAACAGACCGAAACCTTAATACAACCTTCTTTGACCCTGCAGGA
GGAGGAGACCCAATTCTTTACCAACACTTATTT`,
  },
  {
    id: 'thunnus-albacares',
    species: 'Thunnus albacares (황다랑어)',
    marker: 'COI',
    description: '참치류 — COI 한계 + D-loop 대안 마커 추천 체험',
    sequence: `>Example_Thunnus_albacares_COI
CCTCTATCTGGTGTTTGGTGCCTGAGCCGGAATGGTCGGCACAGCCCTAAG
CCTACTAATTCGAGCTGAGCTAAGTCAACCCGGCGCCCTTCTAGGTGATGAC
CAAATCTATAATGTAATCGTCACAGCACATGCCTTTGTAATAATTTTCTTTAT
AGTAATACCAATTATAATTGGAGGATTTGGAAACTGACTAATTCCCCTAATG
ATCGGAGCCCCAGATATAGCATTCCCTCGAATAAATAACATAAGCTTCTGACT
TCTCCCCCCATCATTCCTCCTTCTCCTAGCCTCTTCTGGAGTAGAAGCTGGAG
CAGGTACAGGATGAACTGTATATCCCCCCCTATCAGGCAACCTAGCCCATGCC
GGAGCATCAGTTGATCTAACAATTTTCTCACTCCACCTGGCAGGTGTCTCATC
AATTCTAGGCGCAATTAACTTTATTACAACAATCATTAACATGAAACCCCCAG
CCATTTCTCAGTATCAAACACCCCTGTTTGTGTGAGCAGTCCTAATTACAGCC
GTACTACTCCTCCTATCCCTTCCAGTCCTCGCCGCCGGCATTACAATGCTTTT
AACAGACCGAAACCTAAATACAACCTTCTTTGACCCTGCAGGAGGAGGAGACC
CCATTCTTTACCAACACTTATTC`,
  },
  {
    id: 'saccharomyces',
    species: 'Saccharomyces cerevisiae (효모)',
    marker: 'ITS',
    description: '진균 바코딩 — ITS 마커 사용 사례',
    sequence: `>Example_Saccharomyces_cerevisiae_ITS
AAGGATCATTAATGAATAAACTTGTGGATTTTTATTGAATTATCAACTAATAC
GCGAATCCATCAAATTTTTGTCCTTCGATAGTGAAATTATCAATGCGCCATAA
TGATCCTCAAAATTGTATTAAAGTTTCCATTAGAAATGTTTTAATTTATCAAAT
TTAATTAATGTAAAAAACTCCCATTATTTCAACGAGATTTATAACTAAAACAAA
CTTTCAACAACGGATCTCTTGGCTCTCGCATCGATGAAGAACGCAGCGAAATG
CGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCA
CCTTGCGCTCCTTGGTATTCCGAGGAGCATGCCTGTTTGAGTGTCATGAAATT
CTCAACCCCCCCTTTTTTTTCAAGGTTGACCTCGGATCAGGTAGGAATACCCGC
TGAACTTAAGCATATCAATAAGCGGAGGAAAAGAAACTAACAAGGATTCCCCTA
GTAACTGCGAGTGAAGCGGGAAAAAGCTCAAATTTAAAATCTGGCAGTCTTTG
GCCGTCCGAGTTGTAATCTGGAGAAGTCGTAACAAGGTTTCCGTAGGTGAACC
TGCGGAAGGATCATTAATGAATAAACTTGTGGATTTTTATTGAAT`,
  },
  {
    id: 'rana-temporaria-16s',
    species: 'Rana temporaria (유럽갈색개구리)',
    marker: '16S',
    description: '양서류 바코딩 — 16S rRNA 마커, 환경DNA 분석 사례',
    sequence: `>Example_Rana_temporaria_16S
ACAAAGACTTGTCCTTTAAATTAACTAATGGAGCTGGTATCAGGCACACCAA
CAAGTCAGCCCAAGACACCTTGCTAAGCCACACCCCCAAGGGAACTCAGCAG
TGATAAATATTGAGCAATAAGTGAAAACTTGACTTAGTTATAGCTAAAAGAG
CCGGTAAAACTCGTGCCAGCCACCGCGGTTACACGAAAGGGCTTAAATTGAT
ATTACACGGCGTAAAGCGTGATTAGAGAATAAAATAAACTAAAGCCAAACACT
TCCAAAGCTGTTATACGCATCCGAAGACACGAAGCCCCAC`,
  },
  {
    id: 'oncorhynchus-12s',
    species: 'Oncorhynchus mykiss (무지개송어)',
    marker: '12S',
    description: '어류 eDNA — 12S rRNA 짧은 단편, 열화 시료 적합',
    sequence: `>Example_Oncorhynchus_mykiss_12S
ACAAAGCATGGCACTGAAGATGCCAAGATGGCTGTATAGATATATCACAGCA
CCAAAGACTTGGTCCTGGCCTTAATAATTAATTAGAGGTAAAATTACACATG
CAAGTATCCGCACCCCAGTGAGAATGCCCTAATTAATCTACCAGATCAATAG
GAGCAGGTATCAGGCACACCAAACAAAGTAGCCCATAACACCTTGCTTAGCC
ACACCCCCAAGGGAACTCAGCAGTGATAAATATTGAACAATAAACGAAAGTT
TGACTAAGTTATACCTCATAGGGCCGGTAA`,
  },
  {
    id: 'myotis-lucifugus-cytb',
    species: 'Myotis lucifugus (작은갈색박쥐)',
    marker: 'CytB',
    description: '포유류 바코딩 — Cytochrome b, 법의학 시료 분석',
    sequence: `>Example_Myotis_lucifugus_CytB
ATGACCAACATCCGAAAAACCCACCCACTAATAAAAATTGTAAACAACGCAT
TCATTGATCTCCCAGCCCCATCAAATATTTCATCATGATGAAATTTTGGATC
CCTACTAGGAATTTGCCTAATTTTACAAATTCTAACAGGCCTATTCCTAGCA
ATACACTACACATCAGACACAATAACAGCATTCTCTTCAGTCACACATATTTG
TCGAGATGTAAATTATGGCTGACTCATCCGATATATACACGCAAACGGGGCC
TCAATATTTTTTATCTGCCTATTTATTCACGTCGGACGAGGCCTATATTACG
GCTCATTTACACTTTTCGAAACATGAAACATTGGAATTGTACTATTACTTCT
AACTATAATAACAGCATTCATAGGCTATGTACTACCATGA`,
  },
  {
    id: 'thunnus-thynnus-dloop',
    species: 'Thunnus thynnus (대서양참다랑어)',
    marker: 'D-loop',
    description: '참치류 종 세분화 — D-loop, COI로 구분 어려운 근연종 판별',
    sequence: `>Example_Thunnus_thynnus_Dloop
TTACTAATGTATTCGTACATATATGTATTATCACCATTAATTTATTTTAACCA
TAAAGCAAGTACTAAATATCAAGACATATACATAAACATAATATTTAAGACTC
AACATAATTTGTTTAAACCCAGTTATATATTATTCCCCAACAATTTATTTTAA
CCTCATTAATCTAGTATTAGTAAATCCATAACATGACTATCCCTCACCAATGG
ATATCCTCTGATAATCCCAAATAAATTGATCTAGCATATCATATCAAATCTTA
ACAAACTTTAATCAAGATTTACGACAACCATCAGAATGATTTCTTAATGATAA
CCTCCCTATTTATTGATCGTCTCAACATTTAAGTTGACGTCAATCAGACACGG
TTTATCAGTCTGGTTATTACTTTATTGATCGACT`,
  },
]

export function getExampleById(id: string): ExampleSequence | undefined {
  return EXAMPLE_SEQUENCES.find(ex => ex.id === id)
}
