import type { BlastMarker } from '@biohub/types'

export interface ExampleSequence {
  id: string
  species: string
  marker: BlastMarker
  description: string
  sequence: string
}

export const EXAMPLE_SEQUENCES: ExampleSequence[] = [
  {
    id: 'gadus-morhua',
    species: 'Gadus morhua (대구)',
    marker: 'COI',
    description: '동물 바코딩 표준 — 높은 신뢰도 결과 예상',
    sequence: `>Example_Gadus_morhua_COI
CCTCTACCTGGTGTTTGGTGCCTGAGCCGGAATAGTCGGCACAGCTCTAAG
CCTTCTAATTCGAGCTGAGCTGAGCCAACCAGGCGCCCTTCTAGGCGATGA
CCAAATTTATAATGTAATTGTTACAGCACATGCCTTTGTAATAATTTTCTTT
ATAGTAATACCAATTATAATTGGAGGATTTGGAAACTGACTAGTGCCCCTAA
TGATCGGTGCCCCAGACATAGCATTCCCACGAATAAACAACATAAGTTTCTG
ACTTCTCCCTCCATCATTCCTTCTTCTCCTAGCCTCTTCTGGCGTAGAAGCC
GGAGCAGGAACAGGATGAACTGTATATCCCCCCCTATCAGGCAACCTAGCCC
ATGCCGGAGCATCAGTTGATCTAACAATTTTCTCACTCCACCTGGCAGGTGT
CTCATCAATCCTAGGCGCAATCAACTTTATTACAACAATCATTAACATGAAA
CCCCCAGCCATTTCTCAATACCAAACACCCCTGTTCGTGTGAGCAGTTCTCA
TTACAGCCGTACTACTCCTCCTATCTCTTCCAGTCCTCGCCGCCGGCATTAC
CATGCTTTTAACAGACCGAAACCTTAATACAACCTTCTTTGACCCTGCAGGA
GGAGGAGACCCAATTCTTTACCAACACTTATTT`,
  },
  {
    id: 'thunnus-albacares',
    species: 'Thunnus albacares (황다랑어)',
    marker: 'COI',
    description: '참치류 — COI 한계 + D-loop 대안 마커 추천 체험',
    sequence: `>Example_Thunnus_albacares_COI
CCTCTATCTGGTGTTTGGTGCCTGAGCCGGAATGGTCGGCACAGCCCTAAG
CCTACTAATTCGAGCTGAGCTAAGTCAACCCGGCGCCCTTCTAGGTGATGAC
CAAATCTATAATGTAATCGTCACAGCACATGCCTTTGTAATAATTTTCTTTAT
AGTAATACCAATTATAATTGGAGGATTTGGAAACTGACTAATTCCCCTAATG
ATCGGAGCCCCAGATATAGCATTCCCTCGAATAAATAACATAAGCTTCTGACT
TCTCCCCCCATCATTCCTCCTTCTCCTAGCCTCTTCTGGAGTAGAAGCTGGAG
CAGGTACAGGATGAACTGTATATCCCCCCCTATCAGGCAACCTAGCCCATGCC
GGAGCATCAGTTGATCTAACAATTTTCTCACTCCACCTGGCAGGTGTCTCATC
AATTCTAGGCGCAATTAACTTTATTACAACAATCATTAACATGAAACCCCCAG
CCATTTCTCAGTATCAAACACCCCTGTTTGTGTGAGCAGTCCTAATTACAGCC
GTACTACTCCTCCTATCCCTTCCAGTCCTCGCCGCCGGCATTACAATGCTTTT
AACAGACCGAAACCTAAATACAACCTTCTTTGACCCTGCAGGAGGAGGAGACC
CCATTCTTTACCAACACTTATTC`,
  },
  {
    id: 'saccharomyces',
    species: 'Saccharomyces cerevisiae (효모)',
    marker: 'ITS',
    description: '진균 바코딩 — ITS 마커 사용 사례',
    sequence: `>Example_Saccharomyces_cerevisiae_ITS
AAGGATCATTAATGAATAAACTTGTGGATTTTTATTGAATTATCAACTAATAC
GCGAATCCATCAAATTTTTGTCCTTCGATAGTGAAATTATCAATGCGCCATAA
TGATCCTCAAAATTGTATTAAAGTTTCCATTAGAAATGTTTTAATTTATCAAAT
TTAATTAATGTAAAAAACTCCCATTATTTCAACGAGATTTATAACTAAAACAAA
CTTTCAACAACGGATCTCTTGGCTCTCGCATCGATGAAGAACGCAGCGAAATG
CGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCA
CCTTGCGCTCCTTGGTATTCCGAGGAGCATGCCTGTTTGAGTGTCATGAAATT
CTCAACCCCCCCTTTTTTTTCAAGGTTGACCTCGGATCAGGTAGGAATACCCGC
TGAACTTAAGCATATCAATAAGCGGAGGAAAAGAAACTAACAAGGATTCCCCTA
GTAACTGCGAGTGAAGCGGGAAAAAGCTCAAATTTAAAATCTGGCAGTCTTTG
GCCGTCCGAGTTGTAATCTGGAGAAGTCGTAACAAGGTTTCCGTAGGTGAACC
TGCGGAAGGATCATTAATGAATAAACTTGTGGATTTTTATTGAAT`,
  },
]

export function getExampleById(id: string): ExampleSequence | undefined {
  return EXAMPLE_SEQUENCES.find(ex => ex.id === id)
}
